#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AB_Survivor_00

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function AB_Survivor_00.AB_Survivor_00_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct AB_Survivor_00_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};

// Function AB_Survivor_00.AB_Survivor_00_C.ExecuteUbergraph_AB_Survivor_00
// 0x0008 (0x0008 - 0x0000)
struct AB_Survivor_00_C_ExecuteUbergraph_AB_Survivor_00 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function AB_Survivor_00.AB_Survivor_00_C.KillerSpecificStatusEffectSurvivorAnimation
// 0x0020 (0x0020 - 0x0000)
struct AB_Survivor_00_C_KillerSpecificStatusEffectSurvivorAnimation final
{
public:
	struct FPoseLink                              InPose;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              KillerSpecificStatusEffectSurvivorAnimation_0;     // 0x0010(0x0010)(Parm, OutParm, NoDestructor)
};

// Function AB_Survivor_00.AB_Survivor_00_C.KillerSpecificSurvivorAnimation
// 0x0020 (0x0020 - 0x0000)
struct AB_Survivor_00_C_KillerSpecificSurvivorAnimation final
{
public:
	struct FPoseLink                              InPose;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              KillerSpecificSurvivorAnimation_0;                 // 0x0010(0x0010)(Parm, OutParm, NoDestructor)
};

// Function AB_Survivor_00.AB_Survivor_00_C.KillerSpecivicSurvivorAnimationAfterMontage
// 0x0020 (0x0020 - 0x0000)
struct AB_Survivor_00_C_KillerSpecivicSurvivorAnimationAfterMontage final
{
public:
	struct FPoseLink                              InPose_;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              KillerSpecivicSurvivorAnimationAfterMontage_0;     // 0x0010(0x0010)(Parm, OutParm, NoDestructor)
};

// Function AB_Survivor_00.AB_Survivor_00_C.Survivor_InteractionUpperBody2_Layer
// 0x0020 (0x0020 - 0x0000)
struct AB_Survivor_00_C_Survivor_InteractionUpperBody2_Layer final
{
public:
	struct FPoseLink                              InPose;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              Survivor_InteractionUpperBody2_Layer_0;            // 0x0010(0x0010)(Parm, OutParm, NoDestructor)
};

// Function AB_Survivor_00.AB_Survivor_00_C.Survivor_InteractionUpperBody_Layer
// 0x0020 (0x0020 - 0x0000)
struct AB_Survivor_00_C_Survivor_InteractionUpperBody_Layer final
{
public:
	struct FPoseLink                              InPose;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              Survivor_InteractionUpperBody_Layer_0;             // 0x0010(0x0010)(Parm, OutParm, NoDestructor)
};

// Function AB_Survivor_00.AB_Survivor_00_C.Survivor_Locomotion_Layer
// 0x0010 (0x0010 - 0x0000)
struct AB_Survivor_00_C_Survivor_Locomotion_Layer final
{
public:
	struct FPoseLink                              Survivor_Locomotion_Layer_0;                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};

// Function AB_Survivor_00.AB_Survivor_00_C.Survivor_Perk_Layer
// 0x0020 (0x0020 - 0x0000)
struct AB_Survivor_00_C_Survivor_Perk_Layer final
{
public:
	struct FPoseLink                              InPose;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              Survivor_Perk_Layer_0;                             // 0x0010(0x0010)(Parm, OutParm, NoDestructor)
};

// Function AB_Survivor_00.AB_Survivor_00_C.SurvivorInteractionCollectableLayer
// 0x0020 (0x0020 - 0x0000)
struct AB_Survivor_00_C_SurvivorInteractionCollectableLayer final
{
public:
	struct FPoseLink                              InPose;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              SurvivorInteractionCollectableLayer_0;             // 0x0010(0x0010)(Parm, OutParm, NoDestructor)
};

// Function AB_Survivor_00.AB_Survivor_00_C.SurvivorInteractionLayer
// 0x0020 (0x0020 - 0x0000)
struct AB_Survivor_00_C_SurvivorInteractionLayer final
{
public:
	struct FPoseLink                              InPose;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              SurvivorInteractionLayer_0;                        // 0x0010(0x0010)(Parm, OutParm, NoDestructor)
};

}

