#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AB_Survivor_M01

#include "Basic.hpp"

#include "AB_Survivor_00_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass AB_Survivor_M01.AB_Survivor_M01_C
// 0x0000 (0x2DD0 - 0x2DD0)
class UAB_Survivor_M01_C final : public UAB_Survivor_00_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AB_Survivor_M01_C">();
	}
	static class UAB_Survivor_M01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAB_Survivor_M01_C>();
	}
};

}

