#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALI_Survivor_Locomotion

#include "Basic.hpp"

#include "ALI_Survivor_Locomotion_classes.hpp"
#include "ALI_Survivor_Locomotion_parameters.hpp"


namespace SDK
{

// Function ALI_Survivor_Locomotion.ALI_Survivor_Locomotion_C.Survivor_Locomotion_Layer
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       Survivor_Locomotion_Layer_0                            (Parm, OutParm, NoDestructor)

void IALI_Survivor_Locomotion_C::Survivor_Locomotion_Layer(struct FPoseLink* Survivor_Locomotion_Layer_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_Survivor_Locomotion_C", "Survivor_Locomotion_Layer");

	Params::ALI_Survivor_Locomotion_C_Survivor_Locomotion_Layer Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (Survivor_Locomotion_Layer_0 != nullptr)
		*Survivor_Locomotion_Layer_0 = std::move(Parms.Survivor_Locomotion_Layer_0);
}

}

