#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Anniversary2023

#include "Basic.hpp"


namespace SDK::Params
{

// Function Anniversary2023.BloodlustExposeInteraction.Cosmetic_BloodlustExpose
// 0x0010 (0x0010 - 0x0000)
struct BloodlustExposeInteraction_Cosmetic_BloodlustExpose final
{
public:
	class ADBDPlayer*                             Player;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class ASurvivor*                              Target;                                            // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Anniversary2023.BloodlustExposeInteraction.Multicast_BloodlustExpose
// 0x0010 (0x0010 - 0x0000)
struct BloodlustExposeInteraction_Multicast_BloodlustExpose final
{
public:
	class ADBDPlayer*                             Player;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class ASurvivor*                              Target;                                            // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Anniversary2023.InvitationKillerComponent.Cosmetic_SetVignetteVisibility
// 0x0001 (0x0001 - 0x0000)
struct InvitationKillerComponent_Cosmetic_SetVignetteVisibility final
{
public:
	bool                                          IsVisible;                                         // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Anniversary2023.KillerNegateStunInteraction.Cosmetic_OnInteractionUpdateStart
// 0x0010 (0x0010 - 0x0000)
struct KillerNegateStunInteraction_Cosmetic_OnInteractionUpdateStart final
{
public:
	class ADBDPlayer*                             interactingPlayer;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AInteractable*                          Interactable;                                      // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Anniversary2023.KillerNegateStunInteraction.OnRep_StatusEffect
// 0x0008 (0x0008 - 0x0000)
struct KillerNegateStunInteraction_OnRep_StatusEffect final
{
public:
	class UStatusEffect*                          previousStatusEffect;                              // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Anniversary2023.RemoteDestroyInteraction.Cosmetic_OnRemoteDestroy
// 0x0010 (0x0010 - 0x0000)
struct RemoteDestroyInteraction_Cosmetic_OnRemoteDestroy final
{
public:
	class ADBDPlayer*                             interactingPlayer;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AInteractable*                          Interactable;                                      // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Anniversary2023.RemoteDestroyInteraction.Multicast_RemoteDestroy
// 0x0010 (0x0010 - 0x0000)
struct RemoteDestroyInteraction_Multicast_RemoteDestroy final
{
public:
	class ADBDPlayer*                             Player;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AInteractable*                          Interactable;                                      // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Anniversary2023.RemoteDestroyInteraction.ExplodeInteractable
// 0x0010 (0x0010 - 0x0000)
struct RemoteDestroyInteraction_ExplodeInteractable final
{
public:
	class ADBDPlayer*                             Player;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AInteractable*                          Interactable;                                      // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Anniversary2023.ReverseBamboozleInteractionDefinition.Cosmetic_OnWindowBlockBegin
// 0x0018 (0x0018 - 0x0000)
struct ReverseBamboozleInteractionDefinition_Cosmetic_OnWindowBlockBegin final
{
public:
	class ADBDPlayer*                             abilityCaster;                                     // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	const class AWindow*                          Window;                                            // 0x0008(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Duration;                                          // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function Anniversary2023.ReverseBamboozleInteractionDefinition.Multicast_OnWindowBlockBegin
// 0x0010 (0x0010 - 0x0000)
struct ReverseBamboozleInteractionDefinition_Multicast_OnWindowBlockBegin final
{
public:
	class ADBDPlayer*                             abilityCaster;                                     // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	const class AWindow*                          Window;                                            // 0x0008(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

