#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BhvrAssetViewer

#include "Basic.hpp"


namespace SDK
{

// Enum BhvrAssetViewer.EBhvrAssetViewRotation
// NumValues: 0x0003
enum class EBhvrAssetViewRotation : uint8
{
	Clockwise                                = 0,
	CounterClockwise                         = 1,
	EBhvrAssetViewRotation_MAX               = 2,
};

// Enum BhvrAssetViewer.EWatermarkLocationPreset
// NumValues: 0x0005
enum class EWatermarkLocationPreset : uint8
{
	TopRight                                 = 0,
	TopLeft                                  = 1,
	BottomRight                              = 2,
	BottomLeft                               = 3,
	EWatermarkLocationPreset_MAX             = 4,
};

// ScriptStruct BhvrAssetViewer.BhvrAssetViewCameraSequence
// 0x0020 (0x0020 - 0x0000)
struct FBhvrAssetViewCameraSequence final
{
public:
	class FString                                 DisplayName;                                       // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class ULevelSequence*                         Sequence;                                          // 0x0010(0x0008)(ZeroConstructor, Transient, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class ALevelSequenceActor*                    SequenceActor;                                     // 0x0018(0x0008)(ZeroConstructor, Transient, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct BhvrAssetViewer.BhvrAssetViewOption
// 0x0028 (0x0028 - 0x0000)
struct FBhvrAssetViewOption final
{
public:
	class FString                                 ID;                                                // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DisplayName;                                       // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTexture2D*                             Thumbnail;                                         // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct BhvrAssetViewer.BhvrBufferVisualizationMaterials
// 0x0010 (0x0010 - 0x0000)
struct FBhvrBufferVisualizationMaterials final
{
public:
	TArray<class FString>                         OutputMaterialNames;                               // 0x0000(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
};

// ScriptStruct BhvrAssetViewer.BhvrScreenshotCaptureRegion
// 0x0010 (0x0010 - 0x0000)
struct FBhvrScreenshotCaptureRegion final
{
public:
	int32                                         MinX;                                              // 0x0000(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         MinY;                                              // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         MaxX;                                              // 0x0008(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         MaxY;                                              // 0x000C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

