#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CamperFemale02_Character

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_CamperFemale02_Character.BP_CamperFemale02_Character_C.ExecuteUbergraph_BP_CamperFemale02_Character
// 0x0004 (0x0004 - 0x0000)
struct BP_CamperFemale02_Character_C_ExecuteUbergraph_BP_CamperFemale02_Character final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

