#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CoreScaleformTooltipsPresenterGroup

#include "Basic.hpp"

#include "DBDUIPresenters_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CoreScaleformTooltipsPresenterGroup.BP_CoreScaleformTooltipsPresenterGroup_C
// 0x0000 (0x0058 - 0x0058)
class UBP_CoreScaleformTooltipsPresenterGroup_C final : public UPresenterGroup
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CoreScaleformTooltipsPresenterGroup_C">();
	}
	static class UBP_CoreScaleformTooltipsPresenterGroup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CoreScaleformTooltipsPresenterGroup_C>();
	}
};

}

