#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_InjureRecentlyBlindingSurvivorAchievement

#include "Basic.hpp"

#include "Achievements_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_InjureRecentlyBlindingSurvivorAchievement.BP_InjureRecentlyBlindingSurvivorAchievement_C
// 0x0000 (0x00C0 - 0x00C0)
class UBP_InjureRecentlyBlindingSurvivorAchievement_C final : public UInjureRecentlyBlindingSurvivorAchievement
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_InjureRecentlyBlindingSurvivorAchievement_C">();
	}
	static class UBP_InjureRecentlyBlindingSurvivorAchievement_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_InjureRecentlyBlindingSurvivorAchievement_C>();
	}
};

}

