#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Key

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "DBDGameplay_classes.hpp"
#include "AkAudio_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Key.BP_Key_C
// 0x0048 (0x05E8 - 0x05A0)
class ABP_Key_C : public ABaseSurvivorCollectable
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USleepingSkinnedMeshRegisterer*         SleepingSkinnedMeshRegisterer;                     // 0x05A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAuraReading_C*                         AuraReading;                                       // 0x05B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAkComponent*                           Ak_Audio_Key;                                      // 0x05B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChargeableComponent*                   Chargeable;                                        // 0x05C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChargerComponent*                      Charger;                                           // 0x05C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         TML_dissolve_Opacity_Dissolve_EE44F9774D3642E0B50B56ADAAC3A2FC; // 0x05D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            TML_dissolve__Direction_EE44F9774D3642E0B50B56ADAAC3A2FC; // 0x05D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5D5[0x3];                                      // 0x05D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     TML_dissolve;                                      // 0x05D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          AllowOpenHatchWhileCharged;                        // 0x05E0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void TML_dissolve__UpdateFunc();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void ReceiveBeginPlay();
	void OnDropped(class ADBDPlayer* droppingPlayer);
	void OnActivateDissolveItem();
	void TML_dissolve__FinishedFunc();
	void ExecuteUbergraph_BP_Key(int32 EntryPoint);
	void TML_dissolve__Event_dissolve__EventFunc();
	void BndEvt__Charger_K2Node_ComponentBoundEvent_150_ChargeStateChangeDelegate__DelegateSignature(bool Empty);
	void Authority_UseCharge(double ChargeToUse);

	float GetUsePercentLeft() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Key_C">();
	}
	static class ABP_Key_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Key_C>();
	}
};

}

