#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_K34TipToeDistraction

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "TheK34_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_K34TipToeDistraction.BP_K34TipToeDistraction_C
// 0x0010 (0x05F0 - 0x05E0)
class ABP_K34TipToeDistraction_C final : public AK34TipToeDistraction
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UActorPathFollowingComponent*           ActorPathFollowing;                                // 0x05E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void Cosmetic_OnFootHitGround();
	void ExecuteUbergraph_BP_K34TipToeDistraction(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_K34TipToeDistraction_C">();
	}
	static class ABP_K34TipToeDistraction_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_K34TipToeDistraction_C>();
	}
};

}

