#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SurvivorPlayerController

#include "Basic.hpp"

#include "DeadByDaylight_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SurvivorPlayerController.BP_SurvivorPlayerController_C
// 0x0030 (0x0A70 - 0x0A40)
class ABP_SurvivorPlayerController_C final : public ADBDPlayerController
{
public:
	class UBPNearestOutsideMapBoundsLocator_C*    BPNearestOutsideMapBoundsLocator;                  // 0x0A40(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UEmblemAnalyticsComponent*              EmblemAnalytics;                                   // 0x0A48(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDBDEmblem_SurvivorUnbroken*            DBDEmblem_SurvivorUnbroken;                        // 0x0A50(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDBDEmblem_SurvivorLightbringer*        DBDEmblem_SurvivorLightbringer;                    // 0x0A58(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDBDEmblem_SurvivorEvader*              DBDEmblem_SurvivorEvader;                          // 0x0A60(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDBDEmblem_SurvivorBenevolent*          DBDEmblem_SurvivorBenevolent;                      // 0x0A68(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SurvivorPlayerController_C">();
	}
	static class ABP_SurvivorPlayerController_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SurvivorPlayerController_C>();
	}
};

}

