#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WindowBlocker_Smoke_Self

#include "Basic.hpp"

#include "DBDGameplay_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_WindowBlocker_Smoke_Self.BP_WindowBlocker_Smoke_Self_C
// 0x0000 (0x02C8 - 0x02C8)
class ABP_WindowBlocker_Smoke_Self_C final : public AParticleBlockFeedback
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_WindowBlocker_Smoke_Self_C">();
	}
	static class ABP_WindowBlocker_Smoke_Self_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_WindowBlocker_Smoke_Self_C>();
	}
};

}

