#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_AB_Slasher_SubGraph_Attack

#include "Basic.hpp"

#include "Aset_Slasher_BaseAttack_structs.hpp"


namespace SDK::Params
{

// Function BPI_AB_Slasher_SubGraph_Attack.BPI_AB_Slasher_SubGraph_Attack_C.SetAttackAnimationFromMainAB
// 0x0078 (0x0078 - 0x0000)
struct BPI_AB_Slasher_SubGraph_Attack_C_SetAttackAnimationFromMainAB final
{
public:
	struct FAset_Slasher_BaseAttack               AttackAnimSet;                                     // 0x0000(0x0078)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
};

}

