#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CloseHatch

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BaseSlasherInteraction_classes.hpp"
#include "DBDSharedTypes_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass CloseHatch.CloseHatch_C
// 0x0010 (0x0780 - 0x0770)
class UCloseHatch_C final : public UBaseSlasherInteraction_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0770(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void OnInteractionUpdateStart(class ADBDPlayer* Player);
	void OnInteractionUpdateMontageReachedMiddle(class ADBDPlayer* Player);
	void OnInteractionUpdateEnd(class ADBDPlayer* Player);
	void ExecuteUbergraph_CloseHatch(int32 EntryPoint);

	bool IsInteractionPossibleBP(const class ADBDPlayer* Player, EInputInteractionType interactionType) const;
	void GetHatchAnimationMontageSlave(class UAnimationMontageSlave** Anim_Montage_Slave) const;
	void GetHatch(class AHatch** Hatch) const;
	void CanSlasherCloseHatch(bool* canClose) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CloseHatch_C">();
	}
	static class UCloseHatch_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCloseHatch_C>();
	}
};

}

