#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ClosetFakeEnter_BP

#include "Basic.hpp"

#include "DBDInteraction_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ClosetFakeEnter_BP.ClosetFakeEnter_BP_C
// 0x0000 (0x07D0 - 0x07D0)
class UClosetFakeEnter_BP_C final : public ULockerFakeEnterInteraction
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ClosetFakeEnter_BP_C">();
	}
	static class UClosetFakeEnter_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UClosetFakeEnter_BP_C>();
	}
};

}

