#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DBDAnalytics

#include "Basic.hpp"

#include "DeadByDaylight_structs.hpp"
#include "GameplayTags_structs.hpp"


namespace SDK::Params
{

// Function DBDAnalytics.PerkAnalyticsLibrary.SendFranklinsConsumeItemAnalytics
// 0x0008 (0x0008 - 0x0000)
struct PerkAnalyticsLibrary_SendFranklinsConsumeItemAnalytics final
{
public:
	class ADBDPlayer*                             previousOwner;                                     // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDAnalytics.PerkAnalyticsLibrary.SendFranklinsHitSurvivorNearDroppedItemAnalytics
// 0x0010 (0x0010 - 0x0000)
struct PerkAnalyticsLibrary_SendFranklinsHitSurvivorNearDroppedItemAnalytics final
{
public:
	class ADBDPlayer*                             hitSurvivor;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class ADBDPlayer*                             Slasher;                                           // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDAnalytics.PerkAnalyticsLibrary.SendKnockoutSurvivorFoundAnalytics
// 0x0010 (0x0010 - 0x0000)
struct PerkAnalyticsLibrary_SendKnockoutSurvivorFoundAnalytics final
{
public:
	class ADBDPlayer*                             findingSurvivor;                                   // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class ADBDPlayer*                             foundSurvivor;                                     // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDAnalytics.PerkAnalyticsLibrary.SendLightbornAuraRevealedAnalytics
// 0x0010 (0x0010 - 0x0000)
struct PerkAnalyticsLibrary_SendLightbornAuraRevealedAnalytics final
{
public:
	class ADBDPlayer*                             revealedPlayer;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class ADBDPlayer*                             Slasher;                                           // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDAnalytics.PerkAnalyticsLibrary.SendTinkererUndetectableHitNearGeneratorAnalytics
// 0x0010 (0x0010 - 0x0000)
struct PerkAnalyticsLibrary_SendTinkererUndetectableHitNearGeneratorAnalytics final
{
public:
	class ADBDPlayer*                             hitPlayer;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class ADBDPlayer*                             Slasher;                                           // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDAnalytics.PerkAnalyticsLibrary.SendTinkererUndetectableInterruptAnalytics
// 0x0010 (0x0010 - 0x0000)
struct PerkAnalyticsLibrary_SendTinkererUndetectableInterruptAnalytics final
{
public:
	class ADBDPlayer*                             interruptedPlayer;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class ADBDPlayer*                             Slasher;                                           // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDAnalytics.PigAnalytics.IncrementRBTKilledCount
// 0x0010 (0x0010 - 0x0000)
struct PigAnalytics_IncrementRBTKilledCount final
{
public:
	class ASurvivor*                              playerKilled;                                      // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          killedByExecutionZone;                             // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function DBDAnalytics.PigAnalytics.IncrementRBTTimerActived
// 0x0008 (0x0008 - 0x0000)
struct PigAnalytics_IncrementRBTTimerActived final
{
public:
	class ASurvivor*                              attachedPlayer;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDAnalytics.PigAnalytics.OnRBTAttached_Analytics
// 0x0010 (0x0010 - 0x0000)
struct PigAnalytics_OnRBTAttached_Analytics final
{
public:
	class AKiller*                                attacher;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class ASurvivor*                              attachee;                                          // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDAnalytics.PigAnalytics.RecordRBTSearch
// 0x0010 (0x0010 - 0x0000)
struct PigAnalytics_RecordRBTSearch final
{
public:
	class ASurvivor*                              searchingPlayer;                                   // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Success;                                           // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function DBDAnalytics.PlayerMovementAnalyticsComponent.OnControllerPossessionChanged
// 0x0010 (0x0010 - 0x0000)
struct PlayerMovementAnalyticsComponent_OnControllerPossessionChanged final
{
public:
	class APawn*                                  OldPawn;                                           // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class APawn*                                  NewPawn;                                           // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDAnalytics.PulldownAnalytics.IncrementPalletDestroy
// 0x0008 (0x0008 - 0x0000)
struct PulldownAnalytics_IncrementPalletDestroy final
{
public:
	class AKiller*                                Killer;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDAnalytics.PulldownAnalytics.IncrementPalletDrop
// 0x0008 (0x0008 - 0x0000)
struct PulldownAnalytics_IncrementPalletDrop final
{
public:
	class ASurvivor*                              Survivor;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDAnalytics.PulldownAnalytics.IncrementPalletSpawned
// 0x0008 (0x0008 - 0x0000)
struct PulldownAnalytics_IncrementPalletSpawned final
{
public:
	class AActor*                                 Actor;                                             // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDAnalytics.PulldownAnalytics.IncrementPalletStun
// 0x0008 (0x0008 - 0x0000)
struct PulldownAnalytics_IncrementPalletStun final
{
public:
	class ASurvivor*                              Survivor;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDAnalytics.SurvivorExposerAnalyticsComponent.OnSurvivorExposerDespawned
// 0x0040 (0x0040 - 0x0000)
struct SurvivorExposerAnalyticsComponent_OnSurvivorExposerDespawned final
{
public:
	struct FGameplayTag                           gameEventType;                                     // 0x0000(0x000C)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameEventData                         GameEventData;                                     // 0x0010(0x0030)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function DBDAnalytics.SurvivorExposerAnalyticsComponent.OnSurvivorExposerSpawned
// 0x0040 (0x0040 - 0x0000)
struct SurvivorExposerAnalyticsComponent_OnSurvivorExposerSpawned final
{
public:
	struct FGameplayTag                           gameEventType;                                     // 0x0000(0x000C)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameEventData                         GameEventData;                                     // 0x0010(0x0030)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function DBDAnalytics.SurvivorInteractionAnalytics.IncrementHealCount
// 0x0008 (0x0008 - 0x0000)
struct SurvivorInteractionAnalytics_IncrementHealCount final
{
public:
	class ASurvivor*                              Survivor;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDAnalytics.SurvivorInteractionAnalytics.RecordHatchEscape
// 0x0008 (0x0008 - 0x0000)
struct SurvivorInteractionAnalytics_RecordHatchEscape final
{
public:
	class ASurvivor*                              Survivor;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDAnalytics.SurvivorInteractionAnalytics.RecordHealSuccess
// 0x0008 (0x0008 - 0x0000)
struct SurvivorInteractionAnalytics_RecordHealSuccess final
{
public:
	class ASurvivor*                              Survivor;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

