#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DBDCosmetic

#include "Basic.hpp"


namespace SDK::Params
{

// Function DBDCosmetic.DBDCosmeticModuleUtilities.GetCosmeticHelperActorsOfSurvivor
// 0x0018 (0x0018 - 0x0000)
struct DBDCosmeticModuleUtilities_GetCosmeticHelperActorsOfSurvivor final
{
public:
	const class ASurvivor*                        Survivor;                                          // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class ASurvivorCosmeticHelperActor*>   ReturnValue;                                       // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};

// Function DBDCosmetic.DBDCosmeticModuleUtilities.GetCosmeticHelperActorsOfSurvivorByClass
// 0x0020 (0x0020 - 0x0000)
struct DBDCosmeticModuleUtilities_GetCosmeticHelperActorsOfSurvivorByClass final
{
public:
	const class ASurvivor*                        Survivor;                                          // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class ASurvivorCosmeticHelperActor> cosmeticHelperActorClassType;                    // 0x0008(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class ASurvivorCosmeticHelperActor*>   ReturnValue;                                       // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};

// Function DBDCosmetic.DBDPlayerCosmeticHelperActor.Cosmetic_OnIsLocallyObservingPlayerChanged
// 0x0001 (0x0001 - 0x0000)
struct DBDPlayerCosmeticHelperActor_Cosmetic_OnIsLocallyObservingPlayerChanged final
{
public:
	bool                                          isLocallyObservingPlayer;                          // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDCosmetic.DBDPlayerCosmeticHelperActor.Cosmetic_OnPlayerLinked
// 0x0008 (0x0008 - 0x0000)
struct DBDPlayerCosmeticHelperActor_Cosmetic_OnPlayerLinked final
{
public:
	class ADBDPlayer*                             playerLinked;                                      // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDCosmetic.DBDPlayerCosmeticHelperActor.GetAudioComponent
// 0x0008 (0x0008 - 0x0000)
struct DBDPlayerCosmeticHelperActor_GetAudioComponent final
{
public:
	class UAkComponent*                           ReturnValue;                                       // 0x0000(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDCosmetic.DBDPlayerCosmeticHelperActor.GetCustomizedSkeletalMesh
// 0x0008 (0x0008 - 0x0000)
struct DBDPlayerCosmeticHelperActor_GetCustomizedSkeletalMesh final
{
public:
	class UCustomizedSkeletalMesh*                ReturnValue;                                       // 0x0000(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDCosmetic.DBDPlayerCosmeticHelperActor.GetMaterialHelper
// 0x0008 (0x0008 - 0x0000)
struct DBDPlayerCosmeticHelperActor_GetMaterialHelper final
{
public:
	class UMaterialHelper*                        ReturnValue;                                       // 0x0000(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDCosmetic.DBDPlayerCosmeticHelperActor.GetPlayer
// 0x0008 (0x0008 - 0x0000)
struct DBDPlayerCosmeticHelperActor_GetPlayer final
{
public:
	class ADBDPlayer*                             ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDCosmetic.DBDPlayerCosmeticHelperActor.IsLocallyObserved
// 0x0001 (0x0001 - 0x0000)
struct DBDPlayerCosmeticHelperActor_IsLocallyObserved final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDCosmetic.DBDPlayerCosmeticHelperSpawnerComponent.GetCosmeticHelperActorByClass
// 0x0018 (0x0018 - 0x0000)
struct DBDPlayerCosmeticHelperSpawnerComponent_GetCosmeticHelperActorByClass final
{
public:
	TSubclassOf<class ADBDPlayerCosmeticHelperActor> cosmeticHelperActorClassType;                   // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class ADBDPlayerCosmeticHelperActor*>  ReturnValue;                                       // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};

// Function DBDCosmetic.DBDPlayerCosmeticHelperSpawnerComponent.GetCosmeticHelperActors
// 0x0010 (0x0010 - 0x0000)
struct DBDPlayerCosmeticHelperSpawnerComponent_GetCosmeticHelperActors final
{
public:
	TArray<class ADBDPlayerCosmeticHelperActor*>  ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};

// Function DBDCosmetic.DBDActorIndicator.Cosmetic_UpdateIndicatorActivationStatus
// 0x0001 (0x0001 - 0x0000)
struct DBDActorIndicator_Cosmetic_UpdateIndicatorActivationStatus final
{
public:
	bool                                          IsActivated;                                       // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDCosmetic.SurvivorCosmeticHelperActor.Cosmetic_OnCosmeticActivationChanged
// 0x0001 (0x0001 - 0x0000)
struct SurvivorCosmeticHelperActor_Cosmetic_OnCosmeticActivationChanged final
{
public:
	bool                                          shouldBeActivated;                                 // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDCosmetic.SurvivorCosmeticHelperActor.Cosmetic_OnIsGettingMoriedStatusChanged
// 0x0001 (0x0001 - 0x0000)
struct SurvivorCosmeticHelperActor_Cosmetic_OnIsGettingMoriedStatusChanged final
{
public:
	bool                                          isGettingMoried;                                   // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDCosmetic.SurvivorCosmeticHelperActor.SetCosmeticActivated
// 0x0001 (0x0001 - 0x0000)
struct SurvivorCosmeticHelperActor_SetCosmeticActivated final
{
public:
	bool                                          IsActivated;                                       // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDCosmetic.SurvivorCosmeticHelperActor.GetSurvivor
// 0x0008 (0x0008 - 0x0000)
struct SurvivorCosmeticHelperActor_GetSurvivor final
{
public:
	class ASurvivor*                              ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDCosmetic.SurvivorCosmeticHelperActor.ShouldCosmeticBeActivated
// 0x0001 (0x0001 - 0x0000)
struct SurvivorCosmeticHelperActor_ShouldCosmeticBeActivated final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

