#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DBDGameplay

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "AIModule_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "DeadByDaylight_structs.hpp"
#include "StatSystem_structs.hpp"


namespace SDK
{

// Enum DBDGameplay.EPassageCosmeticState
// NumValues: 0x0004
enum class EPassageCosmeticState : uint8
{
	Open                                     = 0,
	InUse                                    = 1,
	CLOSED                                   = 2,
	EPassageCosmeticState_MAX                = 3,
};

// Enum DBDGameplay.EKillerPowerSpawnableComponentsParent
// NumValues: 0x0003
enum class EKillerPowerSpawnableComponentsParent : uint8
{
	Killer                                   = 0,
	Power                                    = 1,
	EKillerPowerSpawnableComponentsParent_MAX = 2,
};

// Enum DBDGameplay.EKillerPowerSpawnableComponentsSpawnType
// NumValues: 0x0004
enum class EKillerPowerSpawnableComponentsSpawnType : uint8
{
	Replicated                               = 0,
	Local                                    = 1,
	PureCosmetic                             = 2,
	EKillerPowerSpawnableComponentsSpawnType_MAX = 3,
};

// Enum DBDGameplay.EBubbleShowedPlayerType
// NumValues: 0x0004
enum class EBubbleShowedPlayerType : uint8
{
	AllPlayers                               = 0,
	Killer                                   = 1,
	Survivor                                 = 2,
	EBubbleShowedPlayerType_MAX              = 3,
};

// Enum DBDGameplay.EInteractionOwnerType
// NumValues: 0x0008
enum class EInteractionOwnerType : uint8
{
	SurvivorsSelfInteractor                  = 0,
	OwningSurvivorSelfInteractor             = 1,
	SurvivorsKillerInteractor                = 2,
	SurvivorsHealingInteractor1              = 3,
	OwningSurvivorHealingInteractor          = 4,
	KillersStunInteractor                    = 5,
	OwningKillerPowerInteractor              = 6,
	EInteractionOwnerType_MAX                = 7,
};

// Enum DBDGameplay.ESteamPipeState
// NumValues: 0x0006
enum class ESteamPipeState : uint8
{
	Ready                                    = 0,
	Charged                                  = 1,
	Warning                                  = 2,
	Activated                                = 3,
	Disabled                                 = 4,
	ESteamPipeState_MAX                      = 5,
};

// Enum DBDGameplay.ETeleportLocationStatus
// NumValues: 0x0004
enum class ETeleportLocationStatus : uint8
{
	Invalid                                  = 0,
	PassableLocation                         = 1,
	PerfectLocation                          = 2,
	ETeleportLocationStatus_MAX              = 3,
};

// Enum DBDGameplay.EFatherKeyCardState
// NumValues: 0x0005
enum class EFatherKeyCardState : uint8
{
	None                                     = 0,
	Undiscovered                             = 1,
	Discovered                               = 2,
	Secured                                  = 3,
	EFatherKeyCardState_MAX                  = 4,
};

// ScriptStruct DBDGameplay.GroundTargetPlacement
// 0x000C (0x000C - 0x0000)
struct FGroundTargetPlacement final
{
public:
	float                                         _raycastZOffset;                                   // 0x0000(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _raycastLength;                                    // 0x0004(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _maxGroundAngle;                                   // 0x0008(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
};

// ScriptStruct DBDGameplay.PassagePlayerHandles
// 0x0028 (0x0028 - 0x0000)
struct alignas(0x08) FPassagePlayerHandles final
{
public:
	uint8                                         Pad_0[0x28];                                       // 0x0000(0x0028)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct DBDGameplay.TerrorRadiusVisualIndicatorHeartStateRange
// 0x0010 (0x0010 - 0x0000)
struct FTerrorRadiusVisualIndicatorHeartStateRange final
{
public:
	float                                         StartVolume;                                       // 0x0000(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           HeartTag;                                          // 0x0004(0x000C)(Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct DBDGameplay.ActorFailsafeTeleportationData
// 0x0030 (0x0030 - 0x0000)
struct alignas(0x08) FActorFailsafeTeleportationData final
{
public:
	uint8                                         Pad_0[0x30];                                       // 0x0000(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct DBDGameplay.RangedExplosiveEffectData
// 0x0010 (0x0010 - 0x0000)
struct FRangedExplosiveEffectData final
{
public:
	class ARangedExplosive*                       RangedExplosive;                                   // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsInRange;                                         // 0x0008(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          isFirstTime;                                       // 0x0009(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A[0x6];                                        // 0x000A(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct DBDGameplay.SurvivorLookStatus
// 0x0010 (0x0010 - 0x0000)
struct FSurvivorLookStatus final
{
public:
	class ASurvivor*                              OwningSurvivor;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsLookingAtKiller;                                 // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct DBDGameplay.LookingAtData
// 0x0038 (0x0038 - 0x0000)
struct alignas(0x08) FLookingAtData final
{
public:
	uint8                                         Pad_0[0x38];                                       // 0x0000(0x0038)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct DBDGameplay.AimDirection
// 0x0048 (0x0048 - 0x0000)
struct alignas(0x08) FAimDirection final
{
public:
	uint8                                         Pad_0[0x48];                                       // 0x0000(0x0048)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct DBDGameplay.HideHeartIndicatorWithDelay
// 0x0010 (0x0010 - 0x0000)
struct FHideHeartIndicatorWithDelay final
{
public:
	struct FGameplayTag                           HideTag;                                           // 0x0000(0x000C)(Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DelayWhenTagRemoved;                               // 0x000C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct DBDGameplay.RandomAnimationMontage
// 0x0010 (0x0010 - 0x0000)
struct FRandomAnimationMontage final
{
public:
	class UAnimMontage*                           _animationMontage;                                 // 0x0000(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         _randomizationWeight;                              // 0x0008(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct DBDGameplay.ActorTeleportationData
// 0x0050 (0x0050 - 0x0000)
struct FActorTeleportationData final
{
public:
	ETeleportLocationStatus                       TeleportLocationStatus;                            // 0x0000(0x0001)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                BestTeleportLocation;                              // 0x0008(0x0018)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_20[0x30];                                      // 0x0020(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct DBDGameplay.KillerPowerSpawnableComponents
// 0x0010 (0x0010 - 0x0000)
struct FKillerPowerSpawnableComponents final
{
public:
	TSubclassOf<class UActorComponent>            ComponentClass;                                    // 0x0000(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EKillerPowerSpawnableComponentsSpawnType      SpawnType;                                         // 0x0008(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EKillerPowerSpawnableComponentsParent         Parent;                                            // 0x0009(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          AllowMultipleComponentsOfSameClass;                // 0x000A(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_B[0x5];                                        // 0x000B(0x0005)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct DBDGameplay.KillerPowerSpawnableStatusEffectData
// 0x0010 (0x0010 - 0x0000)
struct FKillerPowerSpawnableStatusEffectData final
{
public:
	TSubclassOf<class UStatusEffect>              StatusEffectClass;                                 // 0x0000(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         CustomParam;                                       // 0x0008(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct DBDGameplay.AITerrorEvent
// 0x0030 (0x0030 - 0x0000)
struct FAITerrorEvent final
{
public:
	struct FVector                                Location;                                          // 0x0000(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor*                                 Instigator;                                        // 0x0018(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTerrorRadiusEmitterComponent*          TerrorEmitter;                                     // 0x0020(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGenericTeamId                         TeamIdentifier;                                    // 0x0028(0x0001)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct DBDGameplay.DBDBidirectionalTimer
// 0x0000 (0x0028 - 0x0028)
struct FDBDBidirectionalTimer final : public FDBDTimer
{
};

// ScriptStruct DBDGameplay.BlindTargetViewData
// 0x0070 (0x0070 - 0x0000)
struct alignas(0x10) FBlindTargetViewData final
{
public:
	uint8                                         Pad_0[0x70];                                       // 0x0000(0x0070)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct DBDGameplay.BlockFeedbackStyleOverride
// 0x0030 (0x0030 - 0x0000)
struct FBlockFeedbackStyleOverride final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class ABlockFeedbackBase*>             BlockSelfFeedbacks;                                // 0x0010(0x0010)(ZeroConstructor, Transient, NativeAccessSpecifierPublic)
	TArray<class ABlockFeedbackBase*>             BlockOtherFeedbacks;                               // 0x0020(0x0010)(ZeroConstructor, Transient, NativeAccessSpecifierPublic)
};

// ScriptStruct DBDGameplay.FootstepSpawnParameters
// 0x0020 (0x0020 - 0x0000)
struct FFootstepSpawnParameters final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	class UCurveFloat*                            FadeCurve;                                         // 0x0010(0x0008)(ZeroConstructor, Transient, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCurveFloat*                            VeinsCurve;                                        // 0x0018(0x0008)(ZeroConstructor, Transient, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct DBDGameplay.Footstep
// 0x0058 (0x0058 - 0x0000)
struct FFootstep final
{
public:
	uint8                                         Pad_0[0x20];                                       // 0x0000(0x0020)(Fixing Size After Last Property [ Dumper-7 ])
	class UCurveFloat*                            FadeCurve;                                         // 0x0020(0x0008)(ZeroConstructor, Transient, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCurveFloat*                            VeinsCurve;                                        // 0x0028(0x0008)(ZeroConstructor, Transient, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_30[0x18];                                      // 0x0030(0x0018)(Fixing Size After Last Property [ Dumper-7 ])
	class UDBDDecalComponent*                     _decal;                                            // 0x0048(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_50[0x8];                                       // 0x0050(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct DBDGameplay.ForAllSurvivorsStatusEffectImposer
// 0x0018 (0x0018 - 0x0000)
struct FForAllSurvivorsStatusEffectImposer final
{
public:
	TSubclassOf<class UStatusEffect>              _effectClass;                                      // 0x0000(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_8[0x10];                                       // 0x0008(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct DBDGameplay.CustomKillerInstinctData
// 0x0028 (0x0028 - 0x0000)
struct FCustomKillerInstinctData final
{
public:
	class UNiagaraSystem*                         ParticleSystemAsset;                               // 0x0000(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FGameplayTag>                   SurvivorStateTags;                                 // 0x0008(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
	TArray<struct FGameplayTag>                   KillerStateTags;                                   // 0x0018(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
};

// ScriptStruct DBDGameplay.LockerJumpScarePropStruct
// 0x0018 (0x0018 - 0x0000)
struct FLockerJumpScarePropStruct final
{
public:
	TSubclassOf<class AActor>                     PropActorClass;                                    // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   SocketName;                                        // 0x0008(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct DBDGameplay.LullabyKillerData
// 0x0028 (0x0028 - 0x0000)
struct FLullabyKillerData final
{
public:
	struct FGameplayTag                           KillerPresenceTag;                                 // 0x0000(0x000C)(Edit, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           KillerLullabyActivationState;                      // 0x000C(0x000C)(Edit, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           SurvivorLullabyActivationState;                    // 0x0018(0x000C)(Edit, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         KillerLullabyDistance;                             // 0x0024(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct DBDGameplay.TestableStat
// 0x0008 (0x0088 - 0x0080)
struct FTestableStat final : public FTunableStat
{
public:
	uint8                                         Pad_80[0x8];                                       // 0x0080(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct DBDGameplay.TestableStatModifier
// 0x0000 (0x0030 - 0x0030)
struct FTestableStatModifier final : public FStatModifier
{
};

}

