#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DBDUIManagers

#include "Basic.hpp"

#include "DBDSharedTypes_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "InputCore_structs.hpp"
#include "DBDUIManagers_structs.hpp"


namespace SDK::Params
{

// Function DBDUIManagers.DBDTextManager.GetLargeTextEnabled
// 0x0001 (0x0001 - 0x0000)
struct DBDTextManager_GetLargeTextEnabled final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDUIManagers.UIDataManager.GetChallengeTrackerSkinData
// 0x0058 (0x0058 - 0x0000)
struct UIDataManager_GetChallengeTrackerSkinData final
{
public:
	EChallengeSetType                             ChallengeSetType;                                  // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FChallengeTrackerSkinData              ReturnValue;                                       // 0x0008(0x0050)(ConstParm, Parm, OutParm, ReturnParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function DBDUIManagers.UIDataManager.GetAlertRewardEventSkinData
// 0x0030 (0x0030 - 0x0000)
struct UIDataManager_GetAlertRewardEventSkinData final
{
public:
	class FString                                 EventThemeLabel;                                   // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FAlertRewardEventSkinData              ReturnValue;                                       // 0x0010(0x0020)(Parm, OutParm, ReturnParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function DBDUIManagers.UIDataManager.GetCurrencyIcon
// 0x0040 (0x0040 - 0x0000)
struct UIDataManager_GetCurrencyIcon final
{
public:
	ECurrencyType                                 currencyType;                                      // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UTexture2D>              ReturnValue;                                       // 0x0008(0x0038)(Parm, OutParm, ReturnParm, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDUIManagers.UIDataManager.GetCustomizationRarityMaterial
// 0x0010 (0x0010 - 0x0000)
struct UIDataManager_GetCustomizationRarityMaterial final
{
public:
	EItemRarity                                   Rarity;                                            // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInterface*                     ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDUIManagers.UIDataManager.GetInboxSkinUIData
// 0x0048 (0x0048 - 0x0000)
struct UIDataManager_GetInboxSkinUIData final
{
public:
	class FString                                 inboxSkinLabel;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FInboxSkinUIData                       ReturnValue;                                       // 0x0010(0x0038)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};

// Function DBDUIManagers.UIDataManager.GetInputPromptControlModeData
// 0x0058 (0x0058 - 0x0000)
struct UIDataManager_GetInputPromptControlModeData final
{
public:
	EControlMode                                  controlMode;                                       // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<struct FKey, struct FInputPromptDataRow> ReturnValue;                                       // 0x0008(0x0050)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};

// Function DBDUIManagers.UIDataManager.GetLoadoutPartRarityMaterial
// 0x0040 (0x0040 - 0x0000)
struct UIDataManager_GetLoadoutPartRarityMaterial final
{
public:
	EItemRarity                                   Rarity;                                            // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ELoadoutSlot                                  slotIndex;                                         // 0x0001(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UMaterialInterface>      ReturnValue;                                       // 0x0008(0x0038)(Parm, OutParm, ReturnParm, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDUIManagers.UIDataManager.GetLoadoutPartStatusEffectMaterial
// 0x0040 (0x0040 - 0x0000)
struct UIDataManager_GetLoadoutPartStatusEffectMaterial final
{
public:
	EStatusEffectType                             StatusEffect;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ELoadoutSlot                                  slotIndex;                                         // 0x0001(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UMaterialInterface>      ReturnValue;                                       // 0x0008(0x0038)(Parm, OutParm, ReturnParm, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDUIManagers.UIDataManager.GetProgressionIcon
// 0x0040 (0x0040 - 0x0000)
struct UIDataManager_GetProgressionIcon final
{
public:
	EProgressionType                              ProgressionType;                                   // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UTexture2D>              ReturnValue;                                       // 0x0008(0x0038)(Parm, OutParm, ReturnParm, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDUIManagers.UIDataManager.GetRarityTextColor
// 0x0014 (0x0014 - 0x0000)
struct UIDataManager_GetRarityTextColor final
{
public:
	EItemRarity                                   Rarity;                                            // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           ReturnValue;                                       // 0x0004(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDUIManagers.UIDataManager.GetRarityTint
// 0x0014 (0x0014 - 0x0000)
struct UIDataManager_GetRarityTint final
{
public:
	EItemRarity                                   Rarity;                                            // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           ReturnValue;                                       // 0x0004(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDUIManagers.UIDataManager.GetTooltipEventHeader
// 0x0018 (0x0018 - 0x0000)
struct UIDataManager_GetTooltipEventHeader final
{
public:
	class FString                                 EventBannerLabel;                                  // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTexture2D*                             ReturnValue;                                       // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDUIManagers.UIDataManager.GetTooltipRarityMaterial
// 0x0010 (0x0010 - 0x0000)
struct UIDataManager_GetTooltipRarityMaterial final
{
public:
	EItemRarity                                   Rarity;                                            // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInterface*                     ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDUIManagers.UIScaleManager.GetDPIScaleCurveRatio
// 0x0001 (0x0001 - 0x0000)
struct UIScaleManager_GetDPIScaleCurveRatio final
{
public:
	EDPIScaleCurveRatio                           ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDUIManagers.UIScaleManager.GetHudScaleFactor
// 0x0004 (0x0004 - 0x0000)
struct UIScaleManager_GetHudScaleFactor final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDUIManagers.UIScaleManager.GetMenuScaleFactor
// 0x0004 (0x0004 - 0x0000)
struct UIScaleManager_GetMenuScaleFactor final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDUIManagers.UIScaleManager.GetScaleFactor
// 0x0008 (0x0008 - 0x0000)
struct UIScaleManager_GetScaleFactor final
{
public:
	EScaleType                                    Type;                                              // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         ReturnValue;                                       // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DBDUIManagers.UIScaleManager.GetSkillCheckScaleFactor
// 0x0004 (0x0004 - 0x0000)
struct UIScaleManager_GetSkillCheckScaleFactor final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

