#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EngineSettings

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK
{

// Enum EngineSettings.ETwoPlayerSplitScreenType
// NumValues: 0x0003
enum class ETwoPlayerSplitScreenType : uint8
{
	Horizontal                               = 0,
	Vertical                                 = 1,
	ETwoPlayerSplitScreenType_MAX            = 2,
};

// Enum EngineSettings.EThreePlayerSplitScreenType
// NumValues: 0x0005
enum class EThreePlayerSplitScreenType : uint8
{
	FavorTop                                 = 0,
	FavorBottom                              = 1,
	Vertical                                 = 2,
	Horizontal                               = 3,
	EThreePlayerSplitScreenType_MAX          = 4,
};

// Enum EngineSettings.EFourPlayerSplitScreenType
// NumValues: 0x0004
enum class EFourPlayerSplitScreenType : uint8
{
	Grid                                     = 0,
	Vertical                                 = 1,
	Horizontal                               = 2,
	EFourPlayerSplitScreenType_MAX           = 3,
};

// Enum EngineSettings.ESubLevelStripMode
// NumValues: 0x0003
enum class ESubLevelStripMode : uint8
{
	ExactClass                               = 0,
	IsChildOf                                = 1,
	ESubLevelStripMode_MAX                   = 2,
};

// ScriptStruct EngineSettings.AutoCompleteCommand
// 0x0028 (0x0028 - 0x0000)
struct FAutoCompleteCommand final
{
public:
	class FString                                 Command;                                           // 0x0000(0x0010)(Edit, ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Desc;                                              // 0x0010(0x0010)(Edit, ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_20[0x8];                                       // 0x0020(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct EngineSettings.GameModeName
// 0x0038 (0x0038 - 0x0000)
struct FGameModeName final
{
public:
	class FString                                 Name;                                              // 0x0000(0x0010)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FSoftClassPath                         GameMode;                                          // 0x0010(0x0028)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct EngineSettings.TemplateMapInfoOverride
// 0x0068 (0x0068 - 0x0000)
struct FTemplateMapInfoOverride final
{
public:
	struct FSoftObjectPath                        Thumbnail;                                         // 0x0000(0x0028)(Edit, ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FSoftObjectPath                        Map;                                               // 0x0028(0x0028)(Edit, ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FText                                   DisplayName;                                       // 0x0050(0x0018)(Edit, Config, NativeAccessSpecifierPublic)
};

// ScriptStruct EngineSettings.PathPak
// 0x0028 (0x0028 - 0x0000)
struct FPathPak final
{
public:
	class FString                                 Path;                                              // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 PakName;                                           // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          BringHardDependencies;                             // 0x0020(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          BringSoftDependencies;                             // 0x0021(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_22[0x6];                                       // 0x0022(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct EngineSettings.PakDefinition
// 0x0018 (0x0018 - 0x0000)
struct FPakDefinition final
{
public:
	class FString                                 PakName;                                           // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PakId;                                             // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

}

