#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: InterruptAtInterrupteeLocation

#include "Basic.hpp"

#include "DeadByDaylight_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass InterruptAtInterrupteeLocation.InterruptAtInterrupteeLocation_C
// 0x0010 (0x03F0 - 0x03E0)
class UInterruptAtInterrupteeLocation_C : public UInterruptionDefinition
{
public:
	double                                        Snap_Distance;                                     // 0x03E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	struct FRotator GetInterruptionSnapPointRotationForInterruptor(const class ADBDPlayer* interruptor, const class ADBDPlayer* interruptee) const;
	struct FVector GetInterruptionSnapPointPositionForInterruptor(const class ADBDPlayer* interruptor, const class ADBDPlayer* interruptee) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"InterruptAtInterrupteeLocation_C">();
	}
	static class UInterruptAtInterrupteeLocation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInterruptAtInterrupteeLocation_C>();
	}
};

}

