#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MeshModelingToolsExp

#include "Basic.hpp"


namespace SDK::Params
{

// Function MeshModelingToolsExp.BakeInputMeshProperties.GetSourceUVLayerNamesFunc
// 0x0010 (0x0010 - 0x0000)
struct BakeInputMeshProperties_GetSourceUVLayerNamesFunc final
{
public:
	TArray<class FString>                         ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function MeshModelingToolsExp.BakeInputMeshProperties.GetTargetUVLayerNamesFunc
// 0x0010 (0x0010 - 0x0000)
struct BakeInputMeshProperties_GetTargetUVLayerNamesFunc final
{
public:
	TArray<class FString>                         ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function MeshModelingToolsExp.BakeMeshAttributeMapsToolProperties.GetMapPreviewNamesFunc
// 0x0010 (0x0010 - 0x0000)
struct BakeMeshAttributeMapsToolProperties_GetMapPreviewNamesFunc final
{
public:
	TArray<class FString>                         ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function MeshModelingToolsExp.BakeTexture2DProperties.GetUVLayerNamesFunc
// 0x0010 (0x0010 - 0x0000)
struct BakeTexture2DProperties_GetUVLayerNamesFunc final
{
public:
	TArray<class FString>                         ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function MeshModelingToolsExp.BakeMultiTexture2DProperties.GetUVLayerNamesFunc
// 0x0010 (0x0010 - 0x0000)
struct BakeMultiTexture2DProperties_GetUVLayerNamesFunc final
{
public:
	TArray<class FString>                         ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function MeshModelingToolsExp.BakeMultiMeshAttributeMapsToolProperties.GetMapPreviewNamesFunc
// 0x0010 (0x0010 - 0x0000)
struct BakeMultiMeshAttributeMapsToolProperties_GetMapPreviewNamesFunc final
{
public:
	TArray<class FString>                         ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function MeshModelingToolsExp.BakeMultiMeshInputToolProperties.GetTargetUVLayerNamesFunc
// 0x0010 (0x0010 - 0x0000)
struct BakeMultiMeshInputToolProperties_GetTargetUVLayerNamesFunc final
{
public:
	TArray<class FString>                         ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function MeshModelingToolsExp.BakeRenderCaptureToolProperties.GetMapPreviewNamesFunc
// 0x0010 (0x0010 - 0x0000)
struct BakeRenderCaptureToolProperties_GetMapPreviewNamesFunc final
{
public:
	TArray<class FString>                         ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function MeshModelingToolsExp.BakeRenderCaptureInputToolProperties.GetTargetUVLayerIndex
// 0x0004 (0x0004 - 0x0000)
struct BakeRenderCaptureInputToolProperties_GetTargetUVLayerIndex final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function MeshModelingToolsExp.BakeRenderCaptureInputToolProperties.GetTargetUVLayerNamesFunc
// 0x0010 (0x0010 - 0x0000)
struct BakeRenderCaptureInputToolProperties_GetTargetUVLayerNamesFunc final
{
public:
	TArray<class FString>                         ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function MeshModelingToolsExp.OutputPolygroupLayerProperties.GetGroupOptionsList
// 0x0010 (0x0010 - 0x0000)
struct OutputPolygroupLayerProperties_GetGroupOptionsList final
{
public:
	TArray<class FString>                         ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};

// Function MeshModelingToolsExp.DisplaceMeshCommonProperties.GetWeightMapsFunc
// 0x0010 (0x0010 - 0x0000)
struct DisplaceMeshCommonProperties_GetWeightMapsFunc final
{
public:
	TArray<class FString>                         ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};

// Function MeshModelingToolsExp.SelectiveTessellationProperties.GetMaterialIDsFunc
// 0x0010 (0x0010 - 0x0000)
struct SelectiveTessellationProperties_GetMaterialIDsFunc final
{
public:
	TArray<class FString>                         ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};

// Function MeshModelingToolsExp.MeshAttributePaintToolProperties.GetAttributeNames
// 0x0010 (0x0010 - 0x0000)
struct MeshAttributePaintToolProperties_GetAttributeNames final
{
public:
	TArray<class FString>                         ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function MeshModelingToolsExp.MeshInspectorMaterialProperties.GetUVChannelNamesFunc
// 0x0010 (0x0010 - 0x0000)
struct MeshInspectorMaterialProperties_GetUVChannelNamesFunc final
{
public:
	TArray<class FString>                         ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function MeshModelingToolsExp.TransferMeshToolProperties.GetSourceLODNamesFunc
// 0x0010 (0x0010 - 0x0000)
struct TransferMeshToolProperties_GetSourceLODNamesFunc final
{
public:
	TArray<class FString>                         ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function MeshModelingToolsExp.TransferMeshToolProperties.GetTargetLODNamesFunc
// 0x0010 (0x0010 - 0x0000)
struct TransferMeshToolProperties_GetTargetLODNamesFunc final
{
public:
	TArray<class FString>                         ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)
};

}

