#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OnlinePresence

#include "Basic.hpp"


namespace SDK::Params
{

// Function OnlinePresence.OnlinePresenceExternalCommands.DBD_GenerateTestItems
// 0x0001 (0x0001 - 0x0000)
struct OnlinePresenceExternalCommands_DBD_GenerateTestItems final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function OnlinePresence.OnlinePresenceExternalCommands.DBD_GrantPromoItems
// 0x0001 (0x0001 - 0x0000)
struct OnlinePresenceExternalCommands_DBD_GrantPromoItems final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function OnlinePresence.OnlinePresenceExternalCommands.DBD_IsDlcInstalled
// 0x0018 (0x0018 - 0x0000)
struct OnlinePresenceExternalCommands_DBD_IsDlcInstalled final
{
public:
	class FString                                 InString;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function OnlinePresence.OnlinePresenceExternalCommands.DBD_MirrorsGetValue
// 0x0010 (0x0010 - 0x0000)
struct OnlinePresenceExternalCommands_DBD_MirrorsGetValue final
{
public:
	class FString                                 StateName;                                         // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function OnlinePresence.OnlinePresenceExternalCommands.DBD_MirrorsSaveTestValue
// 0x0018 (0x0018 - 0x0000)
struct OnlinePresenceExternalCommands_DBD_MirrorsSaveTestValue final
{
public:
	class FString                                 StateName;                                         // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Version;                                           // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function OnlinePresence.OnlinePresenceExternalCommands.DBD_MirrorsWalletGetCurrency
// 0x0010 (0x0010 - 0x0000)
struct OnlinePresenceExternalCommands_DBD_MirrorsWalletGetCurrency final
{
public:
	class FString                                 CurrencyName;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function OnlinePresence.OnlinePresenceExternalCommands.DBD_MirrorsWalletWithdraw
// 0x0018 (0x0018 - 0x0000)
struct OnlinePresenceExternalCommands_DBD_MirrorsWalletWithdraw final
{
public:
	class FString                                 CurrencyName;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Value;                                             // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

}

