#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PounceAttackObstructSubstate_BP

#include "Basic.hpp"

#include "DBDAttack_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PounceAttackObstructSubstate_BP.PounceAttackObstructSubstate_BP_C
// 0x0000 (0x0128 - 0x0128)
class UPounceAttackObstructSubstate_BP_C final : public UPounceAttackObstructSubstate
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PounceAttackObstructSubstate_BP_C">();
	}
	static class UPounceAttackObstructSubstate_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPounceAttackObstructSubstate_BP_C>();
	}
};

}

