#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ScoreSlasherPowerK24HitSurvivorAchievementBP

#include "Basic.hpp"

#include "Achievements_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ScoreSlasherPowerK24HitSurvivorAchievementBP.ScoreSlasherPowerK24HitSurvivorAchievementBP_C
// 0x0000 (0x0078 - 0x0078)
class UScoreSlasherPowerK24HitSurvivorAchievementBP_C final : public UScoreK24PowerHitSurvivor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ScoreSlasherPowerK24HitSurvivorAchievementBP_C">();
	}
	static class UScoreSlasherPowerK24HitSurvivorAchievementBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UScoreSlasherPowerK24HitSurvivorAchievementBP_C>();
	}
};

}

