#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StartGameAchievementBP

#include "Basic.hpp"

#include "Achievements_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass StartGameAchievementBP.StartGameAchievementBP_C
// 0x0000 (0x0078 - 0x0078)
class UStartGameAchievementBP_C final : public UStartGameAchievement
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"StartGameAchievementBP_C">();
	}
	static class UStartGameAchievementBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStartGameAchievementBP_C>();
	}
};

}

