#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TheK39

#include "Basic.hpp"

#include "DBDCosmetic_classes.hpp"
#include "GameplayTags_structs.hpp"
#include "AnimationUtilities_structs.hpp"
#include "TheK39_structs.hpp"
#include "GameplayUtilities_classes.hpp"
#include "DBDAnimation_classes.hpp"
#include "DeadByDaylight_structs.hpp"
#include "DeadByDaylight_classes.hpp"
#include "DBDGameplay_classes.hpp"
#include "DBDCompetence_classes.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "DBDSharedTypes_structs.hpp"
#include "StatSystem_structs.hpp"


namespace SDK
{

// Class TheK39.K39KillerCosmeticHelperActor
// 0x0060 (0x0348 - 0x02E8)
class AK39KillerCosmeticHelperActor final : public ADBDPlayerCosmeticHelperActor
{
public:
	uint8                                         Pad_2E8[0x58];                                     // 0x02E8(0x0058)(Fixing Size After Last Property [ Dumper-7 ])
	class UKillerPowerElementsSpawnedDelegate*    _killerPowerElementsSpawnedDelegate;               // 0x0340(0x0008)(ZeroConstructor, Transient, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	void Cosmetic_OnAdjustingAlmostComplete();
	void Cosmetic_OnAdjustingStateEntered();
	void Cosmetic_OnAdjustingTimeExpired();
	void Cosmetic_OnCancelChargeTentacleSwing();
	void Cosmetic_OnMoriStarted();
	void Cosmetic_OnMoriStopped();
	void Cosmetic_OnMovementStarted();
	void Cosmetic_OnMovementStopped();
	void Cosmetic_OnPowerCooldownEnded();
	void Cosmetic_OnPowerUpModeAdded(bool inWithdrawal, float withdrawalTime);
	void Cosmetic_OnPowerUpModeRemoved();
	void Cosmetic_OnQuickTimeEventFailed();
	void Cosmetic_OnQuickTimeEventSucceded();
	void Cosmetic_OnStartChargeTentacleSwing();
	void Cosmetic_OnSurvivorRemovedInfected(class ASurvivor* Survivor);
	void Cosmetic_OnTentacleAttached(class ASurvivor* Survivor, const struct FVector& Location, bool isNonDamaging, class UPhysicalMaterial* PhysicalMaterial, const struct FVector& SurfaceNormal);
	void Cosmetic_OnTentacleLaunched(const bool isSuccess);
	void Cosmetic_OnTentacleRetracting(const struct FVector& Location);
	void Cosmetic_OnTentacleSwingCancelled();
	void Cosmetic_OnTentacleSwingCharged();
	void Cosmetic_OnTentacleSwingEnded();
	void Cosmetic_OnTentacleSwingEndedHitCollision();
	void Cosmetic_OnVaultDamageSurvivor(class ASurvivor* hitSurvivor);
	void Cosmetic_OnWithdrawalEnd(bool isInPowerupMode);
	void Cosmetic_OnWithdrawalPause();
	void Cosmetic_OnWithdrawalStart(float withdrawalTime);
	void Cosmetic_OnWithdrawalUnpause();
	void Cosmetic_UpdateTentacle(const struct FK39TentacleCosmeticSettings& Settings);

	class AK39TentaclesActor* GetTentaclesActor() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39KillerCosmeticHelperActor">();
	}
	static class AK39KillerCosmeticHelperActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<AK39KillerCosmeticHelperActor>();
	}
};

// Class TheK39.K39AnimInstance
// 0x00A0 (0x07C0 - 0x0720)
class UK39AnimInstance final : public UKillerAnimInstance
{
public:
	bool                                          _isAdjusting;                                      // 0x0720(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _isSliding;                                        // 0x0721(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _isLaunchingTentacle;                              // 0x0722(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _isBeingPulled;                                    // 0x0723(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _useBottomTentacles;                               // 0x0724(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _canLaunchSwing;                                   // 0x0725(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _canAttack;                                        // 0x0726(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	EK39TentacleSwingResult                       _tentacleSwingResult;                              // 0x0727(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _isChargingSwing;                                  // 0x0728(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _isInPowerMode;                                    // 0x0729(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _isStunned;                                        // 0x072A(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _isNearHitLocation;                                // 0x072B(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         _isNearHitLocationThreshold;                       // 0x072C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         _swingHeightModifier;                              // 0x0730(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_734[0x4];                                      // 0x0734(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagQuery                      _canLaunchSwingQuery;                              // 0x0738(0x0048)(Edit, EditConst, Protected, NativeAccessSpecifierProtected)
	bool                                          _isObstructed;                                     // 0x0780(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_781[0x7];                                      // 0x0781(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UKillerPowerElementsSpawnedDelegate*    _killerElementsSpawnedDelegate;                    // 0x0788(0x0008)(ZeroConstructor, Transient, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_790[0x30];                                     // 0x0790(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39AnimInstance">();
	}
	static class UK39AnimInstance* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39AnimInstance>();
	}
};

// Class TheK39.K39BaseTentacleSwingState
// 0x0068 (0x00B8 - 0x0050)
class UK39BaseTentacleSwingState : public UBaseReplicatedState
{
public:
	class UK39TentacleSwingAbilityData*           _abilityData;                                      // 0x0050(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_58[0x20];                                      // 0x0058(0x0020)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  _stateTags;                                        // 0x0078(0x0020)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	struct FGameplayTagContainer                  _modifierFlags;                                    // 0x0098(0x0020)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39BaseTentacleSwingState">();
	}
	static class UK39BaseTentacleSwingState* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39BaseTentacleSwingState>();
	}
};

// Class TheK39.K39CancelSwingInteractionDefinition
// 0x0030 (0x07A0 - 0x0770)
class UK39CancelSwingInteractionDefinition final : public UTransientInteractionDefinition
{
public:
	uint8                                         Pad_770[0x30];                                     // 0x0770(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39CancelSwingInteractionDefinition">();
	}
	static class UK39CancelSwingInteractionDefinition* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39CancelSwingInteractionDefinition>();
	}
};

// Class TheK39.K39CancelTentacleSwingAbilityPowerWidgetComponent
// 0x0018 (0x00E8 - 0x00D0)
class UK39CancelTentacleSwingAbilityPowerWidgetComponent final : public UPowerWidgetPresentationComponent
{
public:
	uint8                                         Pad_D0[0x18];                                      // 0x00D0(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39CancelTentacleSwingAbilityPowerWidgetComponent">();
	}
	static class UK39CancelTentacleSwingAbilityPowerWidgetComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39CancelTentacleSwingAbilityPowerWidgetComponent>();
	}
};

// Class TheK39.K39ChargeTentacleSwingInteractionDefinition
// 0x0060 (0x0920 - 0x08C0)
class UK39ChargeTentacleSwingInteractionDefinition final : public UChargeableInteractionDefinition
{
public:
	class UCurveFloat*                            _speedCurve;                                       // 0x08C0(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UChargeableComponent*                   _replicatedChargeableComponent;                    // 0x08C8(0x0008)(ExportObject, Net, ZeroConstructor, InstancedReference, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UK39TentacleSwingAbilityData*           _abilityData;                                      // 0x08D0(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_8D8[0x48];                                     // 0x08D8(0x0048)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnRep_ReplicatedChargeableComponent();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39ChargeTentacleSwingInteractionDefinition">();
	}
	static class UK39ChargeTentacleSwingInteractionDefinition* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39ChargeTentacleSwingInteractionDefinition>();
	}
};

// Class TheK39.K39CheatComponent
// 0x0008 (0x00C0 - 0x00B8)
class UK39CheatComponent final : public UDLCCheatComponent
{
public:
	TSubclassOf<class UStatusEffect>              _k39KillerPowerupModeEffectClass;                  // 0x00B8(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void DBD_K39ActivatePowerupEffect();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39CheatComponent">();
	}
	static class UK39CheatComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39CheatComponent>();
	}
};

// Class TheK39.K39GateBlockerEffect
// 0x0040 (0x03D8 - 0x0398)
class UK39GateBlockerEffect final : public UStatusEffect
{
public:
	TSubclassOf<class UStatusEffect>              _gateBlockerEffectClass;                           // 0x0398(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UK39TentacleSwingAbilityData*           _tentacleSwingAbilityData;                         // 0x03A0(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_3A8[0x30];                                     // 0x03A8(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39GateBlockerEffect">();
	}
	static class UK39GateBlockerEffect* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39GateBlockerEffect>();
	}
};

// Class TheK39.K39KillerPowerupModeEffect
// 0x0098 (0x0430 - 0x0398)
class UK39KillerPowerupModeEffect final : public UStatusEffect
{
public:
	class UK39TentacleSwingAbilityData*           _abilityData;                                      // 0x0398(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_3A0[0x80];                                     // 0x03A0(0x0080)(Fixing Size After Last Property [ Dumper-7 ])
	EK39PowerupModeStatus                         _powerupStatus;                                    // 0x0420(0x0001)(Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_421[0xF];                                      // 0x0421(0x000F)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnRep_PowerupStatus();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39KillerPowerupModeEffect">();
	}
	static class UK39KillerPowerupModeEffect* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39KillerPowerupModeEffect>();
	}
};

// Class TheK39.K39LaunchTentacleInteractionDefinition
// 0x0030 (0x07A0 - 0x0770)
class UK39LaunchTentacleInteractionDefinition final : public UInteractionDefinition
{
public:
	uint8                                         Pad_768[0x38];                                     // 0x0768(0x0038)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39LaunchTentacleInteractionDefinition">();
	}
	static class UK39LaunchTentacleInteractionDefinition* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39LaunchTentacleInteractionDefinition>();
	}
};

// Class TheK39.K39P01
// 0x0040 (0x0520 - 0x04E0)
class UK39P01 final : public UHexPerk
{
public:
	class ATotem*                                 _boundTotem;                                       // 0x04E0(0x0008)(Net, ZeroConstructor, Transient, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	int32                                         _survivorBasicHitsCount;                           // 0x04E8(0x0004)(Net, ZeroConstructor, Transient, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	int32                                         _survivorBasicHitsRequired[0x3];                   // 0x04EC(0x0004)(Edit, EditFixedSize, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TSubclassOf<class UStatusEffect>              _hinderedStatusEffectClass;                        // 0x04F8(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _hinderedAmount[0x3];                              // 0x0500(0x0004)(Edit, EditFixedSize, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _hinderedDuration[0x3];                            // 0x050C(0x0004)(Edit, EditFixedSize, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_518[0x8];                                      // 0x0518(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void Client_UpdateHudIcon(float Percent) const;
	void OnRep_SurvivorBasicHitsCount() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39P01">();
	}
	static class UK39P01* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39P01>();
	}
};

// Class TheK39.K39P02
// 0x0018 (0x0478 - 0x0460)
class UK39P02 final : public UPerk
{
public:
	TSubclassOf<class UStatusEffect>              _K39P02StatusEffectClass;                          // 0x0460(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	int32                                         _maxTokenAmount[0x3];                              // 0x0468(0x0004)(Edit, EditFixedSize, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_474[0x4];                                      // 0x0474(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39P02">();
	}
	static class UK39P02* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39P02>();
	}
};

// Class TheK39.K39P02StatusEffect
// 0x0008 (0x03A0 - 0x0398)
class UK39P02StatusEffect final : public UStatusEffect
{
public:
	float                                         _effectAmountPerToken;                             // 0x0398(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_39C[0x4];                                      // 0x039C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39P02StatusEffect">();
	}
	static class UK39P02StatusEffect* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39P02StatusEffect>();
	}
};

// Class TheK39.K39P03
// 0x0028 (0x0488 - 0x0460)
class UK39P03 final : public UPerk
{
public:
	TArray<class ADBDPlayer*>                     _hookedPlayers;                                    // 0x0460(0x0010)(ZeroConstructor, Transient, NativeAccessSpecifierPrivate)
	float                                         _blockDurationPerToken[0x3];                       // 0x0470(0x0004)(Edit, EditFixedSize, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_47C[0x4];                                      // 0x047C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UStatusEffect>              _survivorStatusEffectClass;                        // 0x0480(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39P03">();
	}
	static class UK39P03* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39P03>();
	}
};

// Class TheK39.K39Power
// 0x0008 (0x0618 - 0x0610)
class AK39Power final : public AKillerPower
{
public:
	class AK39TentaclesActor*                     _tentaclesActor;                                   // 0x0610(0x0008)(ZeroConstructor, Transient, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	class AK39TentaclesActor* GetTentaclesActor() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39Power">();
	}
	static class AK39Power* GetDefaultObj()
	{
		return GetDefaultObjImpl<AK39Power>();
	}
};

// Class TheK39.K39PowerAddon04
// 0x0018 (0x0318 - 0x0300)
class UK39PowerAddon04 final : public UItemAddon
{
public:
	struct FGameplayTag                           _tentacleSwingSpeedIncreaseTag;                    // 0x0300(0x000C)(Edit, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _tentacleSwingSpeedIncreaseValue;                  // 0x030C(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _tentacleSwingSpeedIncreasePercentage;             // 0x0310(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_314[0x4];                                      // 0x0314(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39PowerAddon04">();
	}
	static class UK39PowerAddon04* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39PowerAddon04>();
	}
};

// Class TheK39.K39PowerAddon06
// 0x0018 (0x0318 - 0x0300)
class UK39PowerAddon06 final : public UItemAddon
{
public:
	struct FGameplayTag                           _tentacleSwingSpeedIncreaseTag;                    // 0x0300(0x000C)(Edit, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _tentacleSwingSpeedIncreaseValue;                  // 0x030C(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _tentacleSwingSpeedIncreasePercentage;             // 0x0310(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	bool                                          _isPoweredUp;                                      // 0x0314(0x0001)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_315[0x3];                                      // 0x0315(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39PowerAddon06">();
	}
	static class UK39PowerAddon06* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39PowerAddon06>();
	}
};

// Class TheK39.K39PowerAddon10
// 0x0010 (0x0310 - 0x0300)
class UK39PowerAddon10 final : public UItemAddon
{
public:
	TSubclassOf<class UStatusEffect>              _exhaustedEffectClass;                             // 0x0300(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _exhaustedEffectDuration;                          // 0x0308(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_30C[0x4];                                      // 0x030C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39PowerAddon10">();
	}
	static class UK39PowerAddon10* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39PowerAddon10>();
	}
};

// Class TheK39.K39PowerAddon12
// 0x0010 (0x0310 - 0x0300)
class UK39PowerAddon12 final : public UItemAddon
{
public:
	TSubclassOf<class UStatusEffect>              _auraRevealEffectClass;                            // 0x0300(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _auraRevealEffectDuration;                         // 0x0308(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_30C[0x4];                                      // 0x030C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39PowerAddon12">();
	}
	static class UK39PowerAddon12* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39PowerAddon12>();
	}
};

// Class TheK39.K39PowerAddon13
// 0x0010 (0x0310 - 0x0300)
class UK39PowerAddon13 final : public UItemAddon
{
public:
	TSubclassOf<class UStatusEffect>              _effectClass;                                      // 0x0300(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _effectDuration;                                   // 0x0308(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_30C[0x4];                                      // 0x030C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39PowerAddon13">();
	}
	static class UK39PowerAddon13* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39PowerAddon13>();
	}
};

// Class TheK39.K39PowerAddon15
// 0x0010 (0x0310 - 0x0300)
class UK39PowerAddon15 final : public UItemAddon
{
public:
	TSubclassOf<class UStatusEffect>              _hemorrhageStatusEffectClass;                      // 0x0300(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _hemorrhageStatusEffectDuration;                   // 0x0308(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_30C[0x4];                                      // 0x030C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39PowerAddon15">();
	}
	static class UK39PowerAddon15* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39PowerAddon15>();
	}
};

// Class TheK39.K39PowerAddon16
// 0x0010 (0x0310 - 0x0300)
class UK39PowerAddon16 final : public UItemAddon
{
public:
	float                                         _auraRevealRange;                                  // 0x0300(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _auraRevealDuration;                               // 0x0304(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TSubclassOf<class UStatusEffect>              _auraRevealEffectClass;                            // 0x0308(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39PowerAddon16">();
	}
	static class UK39PowerAddon16* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39PowerAddon16>();
	}
};

// Class TheK39.K39PowerAddon17
// 0x0008 (0x0308 - 0x0300)
class UK39PowerAddon17 final : public UItemAddon
{
public:
	float                                         _blockDuration;                                    // 0x0300(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_304[0x4];                                      // 0x0304(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39PowerAddon17">();
	}
	static class UK39PowerAddon17* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39PowerAddon17>();
	}
};

// Class TheK39.K39PowerAddon18
// 0x0010 (0x0310 - 0x0300)
class UK39PowerAddon18 final : public UItemAddon
{
public:
	TSubclassOf<class UStatusEffect>              _hasteStatusEffectClass;                           // 0x0300(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _hasteStatusEffectAmount;                          // 0x0308(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _hasteStatusEffectDuration;                        // 0x030C(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39PowerAddon18">();
	}
	static class UK39PowerAddon18* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39PowerAddon18>();
	}
};

// Class TheK39.K39PowerAddon19
// 0x0010 (0x0310 - 0x0300)
class UK39PowerAddon19 final : public UItemAddon
{
public:
	float                                         _addonEffectRange;                                 // 0x0300(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_304[0x4];                                      // 0x0304(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         _screamDuration;                                   // 0x0308(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_30C[0x4];                                      // 0x030C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void Multicast_SurvivorScream(const class ASurvivor* Survivor) const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39PowerAddon19">();
	}
	static class UK39PowerAddon19* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39PowerAddon19>();
	}
};

// Class TheK39.K39PowerAddon20
// 0x0008 (0x0308 - 0x0300)
class UK39PowerAddon20 final : public UItemAddon
{
public:
	bool                                          _isOnLastSwing;                                    // 0x0300(0x0001)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_301[0x7];                                      // 0x0301(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void Multicast_DestroyPallet(class APallet* Pallet);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39PowerAddon20">();
	}
	static class UK39PowerAddon20* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39PowerAddon20>();
	}
};

// Class TheK39.K39QuickTimeEventPlayerComponent
// 0x0048 (0x0120 - 0x00D8)
class UK39QuickTimeEventPlayerComponent final : public UQuickTimeEventPlayerComponent
{
public:
	uint8                                         Pad_D8[0x18];                                      // 0x00D8(0x0018)(Fixing Size After Last Property [ Dumper-7 ])
	class UKillerPowerElementsSpawnedDelegate*    _killerElementsSpawnedDelegate;                    // 0x00F0(0x0008)(ZeroConstructor, Transient, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_F8[0x28];                                      // 0x00F8(0x0028)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39QuickTimeEventPlayerComponent">();
	}
	static class UK39QuickTimeEventPlayerComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39QuickTimeEventPlayerComponent>();
	}
};

// Class TheK39.K39ScoringComponent
// 0x00B8 (0x0170 - 0x00B8)
class UK39ScoringComponent final : public UActorComponent
{
public:
	float                                         _windowToHitSurvivorDuration;                      // 0x00B8(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_BC[0xB4];                                      // 0x00BC(0x00B4)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39ScoringComponent">();
	}
	static class UK39ScoringComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39ScoringComponent>();
	}
};

// Class TheK39.K39SlideComponent
// 0x0088 (0x0140 - 0x00B8)
class UK39SlideComponent final : public UActorComponent
{
public:
	class UK39TentacleSwingAbilityData*           _abilityData;                                      // 0x00B8(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FGameplayTagContainer                  _slidingStateTags;                                 // 0x00C0(0x0020)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	class UCurveFloat*                            _slidingSpeedCurve;                                // 0x00E0(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_E8[0x50];                                      // 0x00E8(0x0050)(Fixing Size After Last Property [ Dumper-7 ])
	TWeakObjectPtr<class AKiller>                 _killer;                                           // 0x0138(0x0008)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39SlideComponent">();
	}
	static class UK39SlideComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39SlideComponent>();
	}
};

// Class TheK39.K39SurvivorCosmeticHelperActor
// 0x0040 (0x0398 - 0x0358)
class AK39SurvivorCosmeticHelperActor final : public ASurvivorCosmeticHelperActor
{
public:
	uint8                                         Pad_358[0x38];                                     // 0x0358(0x0038)(Fixing Size After Last Property [ Dumper-7 ])
	class UKillerPowerElementsSpawnedDelegate*    _killerPowerElementsSpawnedDelegate;               // 0x0390(0x0008)(ZeroConstructor, Transient, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	void Cosmetic_OnInfectedAdded();
	void Cosmetic_OnInfectedRemoved();
	void Cosmetic_OnUpdateTargetingReticle(const struct FVector& Location, class ASurvivor* targetedSurvivor, const bool IsNonDamagingSwing, const struct FVector& SurfaceNormal);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39SurvivorCosmeticHelperActor">();
	}
	static class AK39SurvivorCosmeticHelperActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<AK39SurvivorCosmeticHelperActor>();
	}
};

// Class TheK39.K39SurvivorInfectedComponent
// 0x0010 (0x00C8 - 0x00B8)
class UK39SurvivorInfectedComponent final : public UActorComponent
{
public:
	uint8                                         Pad_B8[0x10];                                      // 0x00B8(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39SurvivorInfectedComponent">();
	}
	static class UK39SurvivorInfectedComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39SurvivorInfectedComponent>();
	}
};

// Class TheK39.K39TentacleAnimInstance
// 0x0120 (0x0490 - 0x0370)
class UK39TentacleAnimInstance final : public UDynamicAccessoryAnimInstance
{
public:
	class AKiller*                                _owningKiller;                                     // 0x0368(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class AK39TentaclesActor*                     _tentaclesActor;                                   // 0x0370(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _isLevelReadyToPlay;                               // 0x0378(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _isIntroComplete;                                  // 0x0379(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _isMoving;                                         // 0x037A(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _isLaunchingTentacle;                              // 0x037B(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _isBeingPulled;                                    // 0x037C(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_37D[0x3];                                      // 0x037D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                _hitLocationTop;                                   // 0x0380(0x0018)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FVector                                _hitLocationBot;                                   // 0x0398(0x0018)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	EK39TentacleSwingResult                       _tentacleSwingResult;                              // 0x03B0(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _firstPersonView;                                  // 0x03B1(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _isInAir;                                          // 0x03B2(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_3B3[0x1];                                      // 0x03B3(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         _forwardVelocity;                                  // 0x03B4(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         _lateralVelocity;                                  // 0x03B8(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _isCarrying;                                       // 0x03BC(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	EAttackSubstate                               _attackState;                                      // 0x03BD(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _isChargingSwing;                                  // 0x03BE(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _isInPowerMode;                                    // 0x03BF(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _canLaunchSwing;                                   // 0x03C0(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _useBottomTentacles;                               // 0x03C1(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _canAttack;                                        // 0x03C2(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_3C3[0x1];                                      // 0x03C3(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         _tentacleDistanceTop;                              // 0x03C4(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         _tentacleDistanceBot;                              // 0x03C8(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _isStunned;                                        // 0x03CC(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _isNearHitLocation;                                // 0x03CD(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_3CE[0x2];                                      // 0x03CE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         _isNearHitLocationThreshold;                       // 0x03D0(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         _hitLocationLingeringDuration;                     // 0x03D4(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FGameplayTagQuery                      _canLaunchSwingQuery;                              // 0x03D8(0x0048)(Edit, EditConst, Protected, NativeAccessSpecifierProtected)
	bool                                          _isSliding;                                        // 0x0420(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          _isObstructed;                                     // 0x0421(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_422[0x6E];                                     // 0x0422(0x006E)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnIntroCompleted();
	void OnLevelReadyToPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39TentacleAnimInstance">();
	}
	static class UK39TentacleAnimInstance* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39TentacleAnimInstance>();
	}
};

// Class TheK39.K39TentaclesActor
// 0x0160 (0x0400 - 0x02A0)
class AK39TentaclesActor final : public AActor
{
public:
	uint8                                         Pad_2A0[0x8];                                      // 0x02A0(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UDBDSkeletalMeshComponentBudgeted*      _skeletalMeshComponent;                            // 0x02A8(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, EditConst, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UDBDSkeletalMeshComponentBudgeted*      _longTentaclesMeshComponent;                       // 0x02B0(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, EditConst, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UDBDOutlineComponent*                   _outlineComponentShortTentacles;                   // 0x02B8(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, EditConst, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UDBDOutlineComponent*                   _outlineComponentLongTentacles;                    // 0x02C0(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, EditConst, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UAnimationMontageSlave*                 _montageFollower;                                  // 0x02C8(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UMontagePlayer*                         _montagePlayer;                                    // 0x02D0(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FK39TentacleSkin                       _defaultSkin;                                      // 0x02D8(0x0070)(Edit, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	TMap<class FName, struct FK39TentacleSkin>    _skinOverrides;                                    // 0x0348(0x0050)(Edit, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	struct FGameplayTagQuery                      _shouldShowLongTentaclesTagQuery;                  // 0x0398(0x0048)(Edit, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_3E0[0x8];                                      // 0x03E0(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class USceneComponent*                        _rootComponent;                                    // 0x03E8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TScriptInterface<class IObjectStateProvider>  _stateProvider;                                    // 0x03F0(0x0010)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	void HandleOwningPlayerCustomizationsChanged();
	void SetLongTentaclesVisibility(bool IsVisible);

	class UDBDSkeletalMeshComponentBudgeted* GetLongTentaclesMesh() const;
	class UDBDSkeletalMeshComponentBudgeted* GetMesh() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39TentaclesActor">();
	}
	static class AK39TentaclesActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<AK39TentaclesActor>();
	}
};

// Class TheK39.K39TentacleSwingAbility
// 0x04A8 (0x0688 - 0x01E0)
class UK39TentacleSwingAbility final : public UKillerAbilityComponent
{
public:
	uint8                                         Pad_1E0[0x48];                                     // 0x01E0(0x0048)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class AK39TentacleTargetIndicator> _tentacleTargetIndicatorClass;                    // 0x0228(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class AK39TentacleTargetIndicator*            _tentacleTargetIndicator;                          // 0x0230(0x0008)(ZeroConstructor, Transient, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TSubclassOf<class UInteractionDefinition>     _chargeTentacleInteractionClass;                   // 0x0238(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TSubclassOf<class UInteractionDefinition>     _launchTentacleInteractionClass;                   // 0x0240(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TSubclassOf<class UInteractionDefinition>     _cancelSwingInteractionClass;                      // 0x0248(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_250[0x20];                                     // 0x0250(0x0020)(Fixing Size After Last Property [ Dumper-7 ])
	struct FK39TentacleSwingData                  _cachedTentacleSwingData;                          // 0x0270(0x0070)(Net, NoDestructor, NativeAccessSpecifierPrivate)
	bool                                          _hasSuccessfullySwungAtLeastOnce;                  // 0x02E0(0x0001)(Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	EK39TentacleSwingResult                       _cachedTentacleSwingResult;                        // 0x02E1(0x0001)(Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_2E2[0x6];                                      // 0x02E2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FNonTunableStat                        _maximumTentacleSwingRange;                        // 0x02E8(0x0060)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	struct FNonTunableStat                        _maximumSwingCount;                                // 0x0348(0x0060)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	struct FNonTunableStat                        _adjustingStateDuration;                           // 0x03A8(0x0060)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	struct FNonTunableStat                        _slidingDuration;                                  // 0x0408(0x0060)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	class UTurnLimitationStrategy*                _turnLimitationStrategy;                           // 0x0468(0x0008)(Edit, ExportObject, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, PersistentInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UCurveFloat*                            _mouseLimitationCurve;                             // 0x0470(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UCurveFloat*                            _controllerLimitationCurve;                        // 0x0478(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UCurveFloat*                            _angleDistanceCurve;                               // 0x0480(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UCurveFloat*                            _swingHeightCurve;                                 // 0x0488(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UCurveFloat*                            _swingHeightCurveSurvivor;                         // 0x0490(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _stunFailSafeDuration;                             // 0x0498(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_49C[0xFC];                                     // 0x049C(0x00FC)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimerObject*                           _recentlySwingingTimer;                            // 0x0598(0x0008)(ExportObject, Net, ZeroConstructor, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TSubclassOf<class UStatusEffect>              _k39KillerPowerupModeEffectClass;                  // 0x05A0(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	struct FGameplayTagContainer                  _swingCooldownStateTags;                           // 0x05A8(0x0020)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	uint8                                         Pad_5C8[0x10];                                     // 0x05C8(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         _powerupWithdrawalAdditionalTimer;                 // 0x05D8(0x0004)(Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	bool                                          _hasBegunQuickTimeEvent;                           // 0x05DC(0x0001)(Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_5DD[0xAB];                                     // 0x05DD(0x00AB)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnRep_HasBegunQuickTimeEvent();
	void OnStun(const struct FGameplayTag& GameplayTag, const struct FGameEventData& GameEventData);
	void Server_CacheSwingData(const struct FK39TentacleSwingData& swingData, EK39TentacleSwingResult swingResult);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39TentacleSwingAbility">();
	}
	static class UK39TentacleSwingAbility* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39TentacleSwingAbility>();
	}
};

// Class TheK39.K39TentacleSwingAbilityData
// 0x0190 (0x0200 - 0x0070)
class UK39TentacleSwingAbilityData final : public UKillerAbilityData
{
public:
	float                                         _maximumTentacleSwingRange;                        // 0x0070(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _maximumTentacleSwingRelativeHeight;               // 0x0074(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _maximumTentacleSwingPitch;                        // 0x0078(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _worldDetectionSphereSize;                         // 0x007C(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _survivorDetectionSphereSize;                      // 0x0080(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _survivorDetectionNonDamagingSphereSize;           // 0x0084(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _invalidShowDelay;                                 // 0x0088(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _invalidSwingToSurvivorShowDelay;                  // 0x008C(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _surfaceMinDegreesThreshold;                       // 0x0090(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _surfaceMaxDegreesThreshold;                       // 0x0094(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _minimumSwingDistance;                             // 0x0098(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _minimumSwingDistanceSurvivorFirstSwing;           // 0x009C(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _destinationDistanceBuffer;                        // 0x00A0(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _wallTargetMinimumDegrees;                         // 0x00A4(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _wallTargetMaximumDegrees;                         // 0x00A8(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _tentacleSwingChargeSpeedCurveDuration;            // 0x00AC(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	struct FVector                                _killerEyePositionOffsetFromFeet;                  // 0x00B0(0x0018)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _tentacleSwingSecondsToCharge;                     // 0x00C8(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _tentacleSwingChargeCancelThreshold;               // 0x00CC(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _tentacleSwingAttachingDuration;                   // 0x00D0(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _tentacleSwingRetractingDuration;                  // 0x00D4(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _tentacleSwingMovementSpeedMultiplier;             // 0x00D8(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _tentacleSwingAccelerationMultiplier;              // 0x00DC(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _tentacleSwingCapsuleSize;                         // 0x00E0(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _tentacleSwingCollisionCheckRange;                 // 0x00E4(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _tentacleSwingCollisionCheckCapsuleRadius;         // 0x00E8(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _tentacleSwingCollisionCheckCapsuleHeight;         // 0x00EC(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _adjustingDuration;                                // 0x00F0(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _timeBeforeAdjustingComplete;                      // 0x00F4(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _adjustingSpeedModifier;                           // 0x00F8(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _slidingDuration;                                  // 0x00FC(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _kakuganModeWithdrawalDuration;                    // 0x0100(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _baseWindowTentacleVaultSpeedSeconds;              // 0x0104(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _basePalletTentacleVaultSpeedSeconds;              // 0x0108(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _powerupSwingCooldownModifier;                     // 0x010C(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _powerupAdditionalSwingsModifier;                  // 0x0110(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _powerupTentacleVaultSpeedMultiplier;              // 0x0114(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _firstGrabSurvivorHinderedAmount;                  // 0x0118(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _firstGrabSpeedMultiplier;                         // 0x011C(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TMap<struct FGameplayTag, struct FTentacleSwingCooldownSettings> _cooldownMap;                   // 0x0120(0x0050)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	float                                         _firstGrabMovementSpeedMultiplier;                 // 0x0170(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _firstGrabAccelerationMultiplier;                  // 0x0174(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TSubclassOf<class UStatusEffect>              _firstGrabSurvivorEffectClass;                     // 0x0178(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _successQuickTimeEventWithdrawalTime;              // 0x0180(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_184[0x4];                                      // 0x0184(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  _secondSwingGrabSurvivorStateTags;                 // 0x0188(0x0020)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	float                                         _maxDistanceToTriggerQuickTimeEvent;               // 0x01A8(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _palletVaultAngleVariability;                      // 0x01AC(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _windowVaultAngleVariability;                      // 0x01B0(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _survivorSlowdownLingerTime;                       // 0x01B4(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _survivorSlowdownLingerTimeFromVault;              // 0x01B8(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _recentlySwingingLingerDuration;                   // 0x01BC(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _swingingStrafeMagnitudeRatio;                     // 0x01C0(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _preTentacleShotBufferDuration;                    // 0x01C4(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	struct FQuickTimeEventDefinition              _quickTimeEventDefinition;                         // 0x01C8(0x000C)(Edit, DisableEditOnInstance, NoDestructor, NativeAccessSpecifierPrivate)
	float                                         _survivorRotationTimeWhenGrabbed;                  // 0x01D4(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _swingMotionGracePeriod;                           // 0x01D8(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _swingMotionUnstuckThresholdTime;                  // 0x01DC(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _swingMinimumDistancePerTickToNotBeStuck;          // 0x01E0(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _distanceFromSurvivorOnDamagingGrab;               // 0x01E4(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _grabLookAtTime;                                   // 0x01E8(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _gateBlockerDuration;                              // 0x01EC(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _adjustingGracePeriodDuration;                     // 0x01F0(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _slideMovementControlStrengthRatio;                // 0x01F4(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	int32                                         _tokensToSetOnDestroyPallet;                       // 0x01F8(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_1FC[0x4];                                      // 0x01FC(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39TentacleSwingAbilityData">();
	}
	static class UK39TentacleSwingAbilityData* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39TentacleSwingAbilityData>();
	}
};

// Class TheK39.K39TentacleSwingAbilityPowerWidgetComponent
// 0x0010 (0x00E0 - 0x00D0)
class UK39TentacleSwingAbilityPowerWidgetComponent final : public UPowerWidgetPresentationComponent
{
public:
	uint8                                         Pad_D0[0x10];                                      // 0x00D0(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39TentacleSwingAbilityPowerWidgetComponent">();
	}
	static class UK39TentacleSwingAbilityPowerWidgetComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39TentacleSwingAbilityPowerWidgetComponent>();
	}
};

// Class TheK39.K39TentacleSwingAdjustingState
// 0x00E8 (0x01A0 - 0x00B8)
class UK39TentacleSwingAdjustingState final : public UK39BaseTentacleSwingState
{
public:
	struct FGameplayTagContainer                  _slidingStateTags;                                 // 0x00B8(0x0020)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	class UCurveFloat*                            _slidingSpeedCurve;                                // 0x00D8(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	struct FGameplayTagContainer                  _allowedInteractionSemanticTagsDuringAdjusting;    // 0x00E0(0x0020)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	struct FGameplayTagContainer                  _allowedInteractionSemanticTagsDuringNotRecentlySwinging; // 0x0100(0x0020)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	uint8                                         Pad_120[0x80];                                     // 0x0120(0x0080)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39TentacleSwingAdjustingState">();
	}
	static class UK39TentacleSwingAdjustingState* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39TentacleSwingAdjustingState>();
	}
};

// Class TheK39.K39TentacleSwingAttachingState
// 0x00C8 (0x0180 - 0x00B8)
class UK39TentacleSwingAttachingState final : public UK39BaseTentacleSwingState
{
public:
	struct FAnimationMontageDescriptor            _survivorReactionMontage;                          // 0x00B8(0x0020)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	struct FAnimationMontageDescriptor            _survivorStruggleMontage;                          // 0x00D8(0x0020)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	float                                         _maximumSurvivorHinderedTimeFailsafe;              // 0x00F8(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_FC[0x84];                                      // 0x00FC(0x0084)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39TentacleSwingAttachingState">();
	}
	static class UK39TentacleSwingAttachingState* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39TentacleSwingAttachingState>();
	}
};

// Class TheK39.K39TentacleSwingCooldownState
// 0x0068 (0x0120 - 0x00B8)
class UK39TentacleSwingCooldownState final : public UK39BaseTentacleSwingState
{
public:
	struct FGameplayTag                           _transitionToStateTag;                             // 0x00B8(0x000C)(Edit, DisableEditOnInstance, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_C4[0x3C];                                      // 0x00C4(0x003C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  _allowedInteractionSemanticTagsDuringAdjustingGracePeriod; // 0x0100(0x0020)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39TentacleSwingCooldownState">();
	}
	static class UK39TentacleSwingCooldownState* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39TentacleSwingCooldownState>();
	}
};

// Class TheK39.K39TentacleSwingGrabState
// 0x0178 (0x0230 - 0x00B8)
class UK39TentacleSwingGrabState final : public UK39BaseTentacleSwingState
{
public:
	TSubclassOf<class UStatusEffect>              _k39SurvivorInfectedEffectClass;                   // 0x00B8(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_C0[0x98];                                      // 0x00C0(0x0098)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimationMontageDescriptor            _killerGrabMontage;                                // 0x0158(0x0020)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	struct FAnimationMontageDescriptor            _quickTimeEventSuccessMontage;                     // 0x0178(0x0020)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	struct FAnimationMontageDescriptor            _quickTimeEventFailMontage;                        // 0x0198(0x0020)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	struct FAnimationMontageDescriptor            _quickTimeEventCooldownMontage;                    // 0x01B8(0x0020)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	struct FAnimationMontageDescriptor            _survivorQTESuccessMontage;                        // 0x01D8(0x0020)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	struct FAnimationMontageDescriptor            _survivorQTEFailMontage;                           // 0x01F8(0x0020)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	uint8                                         Pad_218[0x18];                                     // 0x0218(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39TentacleSwingGrabState">();
	}
	static class UK39TentacleSwingGrabState* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39TentacleSwingGrabState>();
	}
};

// Class TheK39.K39TentacleSwingPowerCooldownState
// 0x0040 (0x00F8 - 0x00B8)
class UK39TentacleSwingPowerCooldownState final : public UK39BaseTentacleSwingState
{
public:
	struct FGameplayTagContainer                  _killerStateTagsToRemove;                          // 0x00B8(0x0020)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	struct FAnimationMontageDescriptor            _survivorStruggleMontage;                          // 0x00D8(0x0020)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39TentacleSwingPowerCooldownState">();
	}
	static class UK39TentacleSwingPowerCooldownState* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39TentacleSwingPowerCooldownState>();
	}
};

// Class TheK39.K39TentacleSwingReadyState
// 0x0000 (0x00B8 - 0x00B8)
class UK39TentacleSwingReadyState final : public UK39BaseTentacleSwingState
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39TentacleSwingReadyState">();
	}
	static class UK39TentacleSwingReadyState* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39TentacleSwingReadyState>();
	}
};

// Class TheK39.K39TentacleSwingSwingingState
// 0x0138 (0x01F0 - 0x00B8)
class UK39TentacleSwingSwingingState final : public UK39BaseTentacleSwingState
{
public:
	class UCurveFloat*                            _fovCurve;                                         // 0x00B8(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UCurveFloat*                            _fovCurvePoweredUp;                                // 0x00C0(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	struct FGameplayTagContainer                  _allowedInteractionSemanticTagsDuringSwing;        // 0x00C8(0x0020)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	struct FGameplayTagContainer                  _ignoreCollisionWithPlayerTags;                    // 0x00E8(0x0020)(Edit, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	float                                         _endSwingDestinationDistanceThreshold;             // 0x0108(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_10C[0xE4];                                     // 0x010C(0x00E4)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnSurvivorInOwnerRangeChanged(const bool inRange);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39TentacleSwingSwingingState">();
	}
	static class UK39TentacleSwingSwingingState* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39TentacleSwingSwingingState>();
	}
};

// Class TheK39.K39TentacleTargetIndicator
// 0x0038 (0x02D8 - 0x02A0)
class AK39TentacleTargetIndicator final : public AActor
{
public:
	struct FK39TentacleTargetIndicatorSettings    _settings;                                         // 0x02A0(0x0038)(NoDestructor, NativeAccessSpecifierPrivate)

public:
	void Cosmetic_OnReticleBufferChanged(float bufferPercent);
	void Cosmetic_OnSettingsChanged(const struct FK39TentacleTargetIndicatorSettings& previousSettings, const struct FK39TentacleTargetIndicatorSettings& Settings);
	void Cosmetic_UpdateIndicatorStrength(float distanceModifier);

	struct FK39TentacleTargetIndicatorSettings GetSettings() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39TentacleTargetIndicator">();
	}
	static class AK39TentacleTargetIndicator* GetDefaultObj()
	{
		return GetDefaultObjImpl<AK39TentacleTargetIndicator>();
	}
};

// Class TheK39.K39TentacleTargetingComponent
// 0x0190 (0x0248 - 0x00B8)
class UK39TentacleTargetingComponent final : public UActorComponent
{
public:
	class FName                                   _traceProfile;                                     // 0x00B8(0x000C)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_C4[0x15C];                                     // 0x00C4(0x015C)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   _aimingProfile;                                    // 0x0220(0x000C)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_22C[0xC];                                      // 0x022C(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	class UK39TentacleSwingAbilityData*           _abilityData;                                      // 0x0238(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _survivorReticleOffset;                            // 0x0240(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_244[0x4];                                      // 0x0244(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	struct FK39TentacleSwingData MakeGrabSurvivorSwingData(const struct FVector& HitLocation, const struct FVector& Destination, const struct FVector& CameraDirection, class ASurvivor** TargetSurvivor) const;
	struct FK39TentacleSwingData MakeInvalidSurfaceSwingData(const struct FVector& IndicatorLocation, const struct FVector& SurfaceNormal, const struct FVector& CameraDirection) const;
	struct FK39TentacleSwingData MakeInvalidSwingData(const struct FVector& IndicatorLocation, const struct FVector& CameraDirection) const;
	struct FK39TentacleSwingData MakeValidSwingData(const struct FVector& Destination, const struct FVector& SurfaceNormal, const struct FVector& CollisionPoint, const struct FVector& CameraDirection, class UPhysicalMaterial* PhysicalMaterial) const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39TentacleTargetingComponent">();
	}
	static class UK39TentacleTargetingComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39TentacleTargetingComponent>();
	}
};

// Class TheK39.K39Utilities
// 0x0000 (0x0030 - 0x0030)
class UK39Utilities final : public UBlueprintFunctionLibrary
{
public:
	static bool IsSurvivorAbleToBeAffectedByPower(const class ASurvivor* Survivor, const class AKiller* Killer);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39Utilities">();
	}
	static class UK39Utilities* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39Utilities>();
	}
};

// Class TheK39.K39VaultInteraction
// 0x00F0 (0x0950 - 0x0860)
class UK39VaultInteraction final : public UKillerVaultDefinition
{
public:
	class UK39TentacleSwingAbilityData*           _abilityData;                                      // 0x0860(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TSubclassOf<class UStatusEffect>              _k39SurvivorInfectedEffectClass;                   // 0x0868(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_870[0xE0];                                     // 0x0870(0x00E0)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void Cosmetic_OnTentacleGrabDamage(class ASurvivor* hitSurvivor, const bool isDowned);
	void Multicast_DamageWithTentacle(class ADBDPlayer* Player, class ASurvivor* hitSurvivor, const bool isDowned);
	void Multicast_WillHitSurvivor();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"K39VaultInteraction">();
	}
	static class UK39VaultInteraction* GetDefaultObj()
	{
		return GetDefaultObjImpl<UK39VaultInteraction>();
	}
};

}

