#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TheNurse

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK
{

// Enum TheNurse.EBlinkPowerState
// NumValues: 0x0006
enum class EBlinkPowerState : uint8
{
	Ready                                    = 0,
	ChainBlink                               = 1,
	AttackBlink                              = 2,
	AwaitingCooldown                         = 3,
	Cooldown                                 = 4,
	EBlinkPowerState_MAX                     = 5,
};

// ScriptStruct TheNurse.BlinkParams
// 0x0020 (0x0020 - 0x0000)
struct FBlinkParams final
{
public:
	struct FVector                                TargetTranslation;                                 // 0x0000(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Duration;                                          // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Timestamp;                                         // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

