#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TheS38

#include "Basic.hpp"

#include "DeadByDaylight_structs.hpp"
#include "DeadByDaylight_classes.hpp"
#include "GameplayTags_structs.hpp"
#include "DBDAnimation_classes.hpp"


namespace SDK
{

// Class TheS38.S38P01
// 0x00E8 (0x0548 - 0x0460)
class US38P01 final : public UPerk
{
public:
	uint8                                         Pad_460[0x8];                                      // 0x0460(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UStatusEffect>              _exposedStatusEffectClass;                         // 0x0468(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UStatusEffect*                          _exposedEffect;                                    // 0x0470(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _exposedDuration;                                  // 0x0478(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_47C[0x4];                                      // 0x047C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UStatusEffect>              _hasteStatusEffectClass;                           // 0x0480(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UStatusEffect*                          _hasteEffect;                                      // 0x0488(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _hasteAmount;                                      // 0x0490(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _hasteDuration;                                    // 0x0494(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TSubclassOf<class UStatusEffect>              _exhaustionEffectClass;                            // 0x0498(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UStatusEffect*                          _exhaustionEffect;                                 // 0x04A0(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _exhaustionDuration[0x3];                          // 0x04A8(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_4B4[0x4];                                      // 0x04B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<TSubclassOf<class ACollectable>>       _collectableClasses;                               // 0x04B8(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, UObjectWrapper, NativeAccessSpecifierPrivate)
	TArray<class FName>                           _unsupportedItemAddons;                            // 0x04C8(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	TSubclassOf<class US38P01Interaction>         _interactionBP;                                    // 0x04D8(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _animationDuration;                                // 0x04E0(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_4E4[0x64];                                     // 0x04E4(0x0064)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void Authority_GiveSecondaryPerkEffect();
	void Authority_OnAnimationFinish();
	void Authority_OnPerkActivated(const struct FGameplayTag& gameEventType, const struct FGameEventData& GameEventData);
	void Multicast_OnAnimationStart();
	void Multicast_OnSecondaryPerkEffect(bool shouldScream);

	const TArray<TSubclassOf<class ACollectable>> GetCollectableClasses() const;
	float GetExhaustionDurationAtLevel() const;
	float GetExposedDuration() const;
	float GetHasteAmount() const;
	float GetHasteDuration() const;
	const TArray<class FName> GetUnsupportedItemAddons() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"S38P01">();
	}
	static class US38P01* GetDefaultObj()
	{
		return GetDefaultObjImpl<US38P01>();
	}
};

// Class TheS38.S38P01Interaction
// 0x0010 (0x0780 - 0x0770)
class US38P01Interaction final : public UInteractionDefinition
{
public:
	uint8                                         Pad_768[0x18];                                     // 0x0768(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"S38P01Interaction">();
	}
	static class US38P01Interaction* GetDefaultObj()
	{
		return GetDefaultObjImpl<US38P01Interaction>();
	}
};

// Class TheS38.S38P02
// 0x00D0 (0x0530 - 0x0460)
class US38P02 final : public UPerk
{
public:
	float                                         _percentChanceOfDoubleScream;                      // 0x0460(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_464[0x4];                                      // 0x0464(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  _interactionsNotToInterrupt;                       // 0x0468(0x0020)(Edit, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	TSubclassOf<class UStatusEffect>              _perkStatusEffectClass;                            // 0x0488(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UStatusEffect*                          _perkStatusEffect;                                 // 0x0490(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TSubclassOf<class UStatusEffect>              _auraStatusEffectClass;                            // 0x0498(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _auraDuration[0x3];                                // 0x04A0(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _extraAuraDurationPerExtraScream;                  // 0x04AC(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _screamDuration;                                   // 0x04B0(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _minRandomScreamDelay;                             // 0x04B4(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _maxRandomScreamDelay;                             // 0x04B8(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	int32                                         _maxScreamCount;                                   // 0x04BC(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _cooldownDuration;                                 // 0x04C0(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _preventInteractionDuration;                       // 0x04C4(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_4C8[0x68];                                     // 0x04C8(0x0068)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void Authority_OnIsApplicableChanged(class UGameplayModifierContainer* container, bool IsApplicable_0);
	void Multicast_MakeSurvivorScream(const int32 timesToScream);
	void OnSurvivorScream();

	float GetAuraDurationAtLevel() const;
	float GetCooldownDuration() const;
	float GetExtraAuraDurationPerExtraScream() const;
	float GetMaxRandomScreamDelay() const;
	int32 GetMaxScreamCount() const;
	float GetMinRandomScreamDelay() const;
	float GetScreamDuration() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"S38P02">();
	}
	static class US38P02* GetDefaultObj()
	{
		return GetDefaultObjImpl<US38P02>();
	}
};

// Class TheS38.S38P02StatusEffect
// 0x0010 (0x03A8 - 0x0398)
class US38P02StatusEffect final : public UStatusEffect
{
public:
	class FName                                   _headJointName;                                    // 0x0398(0x000C)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_3A4[0x4];                                      // 0x03A4(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"S38P02StatusEffect">();
	}
	static class US38P02StatusEffect* GetDefaultObj()
	{
		return GetDefaultObjImpl<US38P02StatusEffect>();
	}
};

// Class TheS38.S38P03
// 0x0030 (0x0490 - 0x0460)
class US38P03 final : public UPerk
{
public:
	uint8                                         Pad_460[0x8];                                      // 0x0460(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UStatusEffect>              _onGroundEffectClass;                              // 0x0468(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _hasteDuration[0x3];                               // 0x0470(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_47C[0x4];                                      // 0x047C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class US38P03Interaction>         _interactionBP;                                    // 0x0480(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UInteractionDefinition*                 _perkInteraction;                                  // 0x0488(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	void Authority_OnExitGatesPowered(const struct FGameplayTag& gameEventType, const struct FGameEventData& GameEventData);
	void Authority_OnPerkActivated(const struct FGameplayTag& gameEventType, const struct FGameEventData& GameEventData);
	void Authority_OnPickSelfUp(const struct FGameplayTag& GameplayTag, const struct FGameEventData& GameEventData);

	float GetHasteDurationAtLevel() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"S38P03">();
	}
	static class US38P03* GetDefaultObj()
	{
		return GetDefaultObjImpl<US38P03>();
	}
};

// Class TheS38.S38P03Interaction
// 0x0000 (0x0770 - 0x0770)
class US38P03Interaction final : public UInteractionDefinition
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"S38P03Interaction">();
	}
	static class US38P03Interaction* GetDefaultObj()
	{
		return GetDefaultObjImpl<US38P03Interaction>();
	}
};

// Class TheS38.S38P03OnGroundStatusEffect
// 0x0050 (0x03E8 - 0x0398)
class US38P03OnGroundStatusEffect final : public UStatusEffect
{
public:
	TSubclassOf<class UStatusEffect>              _hasteStatusEffectClass;                           // 0x0398(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _hastePercentage;                                  // 0x03A0(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_3A4[0x4];                                      // 0x03A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UStatusEffect*                          _hasteStatusEffect;                                // 0x03A8(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_3B0[0x38];                                     // 0x03B0(0x0038)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void Authority_HealSelf();
	void Authority_OnHealthStateChanged(EHealthState oldHealthState, EHealthState newHealthState);
	void Authority_OnPickSelfUp(const struct FGameplayTag& gameEventType, const struct FGameEventData& GameEventData);
	void Authority_OnSurvivorHooked(const struct FGameplayTag& gameEventType, const struct FGameEventData& GameEventData);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"S38P03OnGroundStatusEffect">();
	}
	static class US38P03OnGroundStatusEffect* GetDefaultObj()
	{
		return GetDefaultObjImpl<US38P03OnGroundStatusEffect>();
	}
};

// Class TheS38.SurvivorPerkAnimInstance
// 0x0040 (0x0620 - 0x05E0)
class USurvivorPerkAnimInstance : public UBaseSurvivorAnimInstance
{
public:
	struct FGameplayTagContainer                  _tagsToTriggerAnimation;                           // 0x05E0(0x0020)(Edit, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	struct FGameplayTag                           _animationSequenceTag;                             // 0x0600(0x000C)(Edit, DisableEditOnInstance, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_60C[0x4];                                      // 0x060C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimSequence*                          _animationSequence;                                // 0x0610(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          IsInPerkInteraction;                               // 0x0618(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_619[0x7];                                      // 0x0619(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SurvivorPerkAnimInstance">();
	}
	static class USurvivorPerkAnimInstance* GetDefaultObj()
	{
		return GetDefaultObjImpl<USurvivorPerkAnimInstance>();
	}
};

}

