#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VFXUtilities

#include "Basic.hpp"


namespace SDK::Params
{

// Function VFXUtilities.VFXUtilities.SetParticleSystemActive
// 0x0010 (0x0010 - 0x0000)
struct VFXUtilities_SetParticleSystemActive final
{
public:
	class UFXSystemComponent*                     ParticleSystem;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Active;                                            // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Reset;                                             // 0x0009(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A[0x6];                                        // 0x000A(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function VFXUtilities.VFXUtilities.SetParticleSystemsActive
// 0x0058 (0x0058 - 0x0000)
struct VFXUtilities_SetParticleSystemsActive final
{
public:
	TSet<class UFXSystemComponent*>               particleSystems;                                   // 0x0000(0x0050)(Parm, ContainsInstancedReference, NativeAccessSpecifierPublic)
	bool                                          Active;                                            // 0x0050(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Reset;                                             // 0x0051(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_52[0x6];                                       // 0x0052(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

}

