#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ChatWidget

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "DBDUIViewsCore_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_ChatWidget.WBP_ChatWidget_C
// 0x0EB8 (0x1270 - 0x03B8)
class UWBP_ChatWidget_C final : public UCoreChatWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UDBDImage*                              Background;                                        // 0x03C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UDBDImage*                              LeftImage;                                         // 0x03C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UDBDImage*                              LogBGImg;                                          // 0x03D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FColor                                 BlinkInputColor;                                   // 0x03D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3DC[0x4];                                      // 0x03DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FEditableTextBoxStyle                  DefaultInputStyle;                                 // 0x03E0(0x0E80)(Edit, BlueprintVisible, Transient, DisableEditOnInstance)
	class UUITweenInstance*                       CurrentTween;                                      // 0x1260(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void PreConstruct(bool IsDesignTime);
	void OnBlink2(class UUITweenInstance* tween);
	void ExecuteUbergraph_WBP_ChatWidget(int32 EntryPoint);
	void Destruct();
	void Construct();
	void BndEvt__WBP_ChatWidget_ChatInputEditableTB_K2Node_ComponentBoundEvent_0_EditableTextBoxCharacterLimitReachedDelegate__DelegateSignature();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_ChatWidget_C">();
	}
	static class UWBP_ChatWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ChatWidget_C>();
	}
};

}

