#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CoreRankTooltip

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "DBDUIViewsCore_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CoreRankTooltip.WBP_CoreRankTooltip_C
// 0x0018 (0x0368 - 0x0350)
class UWBP_CoreRankTooltip_C final : public UCoreRankTooltipWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0350(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_CoreRankPipsContainer_C*           PipsContainer;                                     // 0x0358(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UDBDImage*                              TitleBgIMG;                                        // 0x0360(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_CoreRankTooltip(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void SetTooltipData(const struct FRankTooltipViewData& ViewData);
	void SetViewData(const struct FRankTooltipViewData& ViewData);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_CoreRankTooltip_C">();
	}
	static class UWBP_CoreRankTooltip_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CoreRankTooltip_C>();
	}
};

}

