#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CoreRewardPopup_VFXWidget

#include "Basic.hpp"

#include "FXWidget_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CoreRewardPopup_VFXWidget.WBP_CoreRewardPopup_VFXWidget_C
// 0x0000 (0x0308 - 0x0308)
class UWBP_CoreRewardPopup_VFXWidget_C final : public UFXUserWidgetBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_CoreRewardPopup_VFXWidget_C">();
	}
	static class UWBP_CoreRewardPopup_VFXWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CoreRewardPopup_VFXWidget_C>();
	}
};

}

