#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CoreKillerStatus

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "DBDUIViewInterfaces_structs.hpp"
#include "DBDUIViewsCore_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CoreKillerStatus.WBP_CoreKillerStatus_C
// 0x00C8 (0x0420 - 0x0358)
class UWBP_CoreKillerStatus_C final : public UCoreKillerStatusWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0358(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UDBDImage*                              ObjectiveSeparator;                                // 0x0360(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_CorePlayerStatus_C*                WBP_CorePlayerStatus;                              // 0x0368(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FPlayerStatusViewData                  CachedViewData;                                    // 0x0370(0x00B0)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void SetPlayerNameVisibility(bool Visible);
	void SetData(const struct FPlayerStatusViewData& Data);
	void ExecuteUbergraph_WBP_CoreKillerStatus(int32 EntryPoint);
	void Construct();
	void ClearData();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_CoreKillerStatus_C">();
	}
	static class UWBP_CoreKillerStatus_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CoreKillerStatus_C>();
	}
};

}

