#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CoreRewardWrapper

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "DBDSharedTypes_structs.hpp"
#include "DBDUIViewsCore_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CoreRewardWrapper.WBP_CoreRewardWrapper_C
// 0x0010 (0x02F0 - 0x02E0)
class UWBP_CoreRewardWrapper_C final : public UCoreRewardWrapperWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	ERewardType                                   ItemType;                                          // 0x02E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_CoreRewardWrapper(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void SetPreviewType(ERewardType RewardType);
	void SetPreviewWidget(ERewardType RewardType);
	void SetSizeOverride(double SizeX, double SizeY);
	void SetWidgetSize(ERewardType ItemType_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_CoreRewardWrapper_C">();
	}
	static class UWBP_CoreRewardWrapper_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CoreRewardWrapper_C>();
	}
};

}

