#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CoreCustomizationItemSlotWrapper

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "DBDUIViewsCore_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CoreCustomizationItemSlotWrapper.WBP_CoreCustomizationItemSlotWrapper_C
// 0x0020 (0x0348 - 0x0328)
class UWBP_CoreCustomizationItemSlotWrapper_C final : public UCoreCustomizationItemSlotWrapper
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0328(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UOverlay*                               CustomizationItemOverlay;                          // 0x0330(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpacer*                                EMPTY_SLOT_REAL_SIZE;                              // 0x0338(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               EmptySlotOverlay;                                  // 0x0340(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_CoreCustomizationItemSlotWrapper(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void SetAsEmptySlot(const bool isEmptySlot);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_CoreCustomizationItemSlotWrapper_C">();
	}
	static class UWBP_CoreCustomizationItemSlotWrapper_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CoreCustomizationItemSlotWrapper_C>();
	}
};

}

